# extras/wezterm/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors]
foreground = "#4f3f2b"
background= "#e3d7aa"
cursor_bg = "#773f0d"
cursor_border = "#773f0d"
cursor_fg= "#e3d7aa"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#7d1e1e"
compose_cursor= "#5d3a17"
scrollbar_thumb= "#d8c688"
visual_bell= "#e0d19f"

ansi = [
  '#424242',
  '#9d1010',
  '#27573d',
  '#544f1c',
  '#114f8c',
  '#681fbd',
  '#2c554f',
  '#44423b',
]

brights = [
  '#48403c',
  '#9d0f0f',
  '#2c5820',
  '#734211',
  '#1e5369',
  '#671fbe',
  '#2b554e',
  '#60380a',
]

[colors.indexed]
16 = '#5d3a17'
17 = '#961e22'

[colors.tab_bar]
background = '#e0d19f'
inactive_tab_edge = '#dccb93'

[colors.tab_bar.active_tab]
bg_color = '#880101'
fg_color = '#e3d7aa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#d8c688'
fg_color = '#880101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d8c688'
fg_color = '#8c4908'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8c4908'
fg_color = '#e3d7aa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#035691'
fg_color = '#e3d7aa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 4'