# extras/wezterm/oasis_midnight_light_4.toml
## name: Oasis Midnight Light 4
## author: uhs-robert

[colors]
foreground = "#4d443e"
background= "#f5d8c7"
cursor_bg = "#9e2023"
cursor_border = "#9e2023"
cursor_fg= "#f5d8c7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#852020"
compose_cursor= "#633d18"
scrollbar_thumb= "#eebda0"
visual_bell= "#f3cfba"

ansi = [
  '#464646',
  '#a51111',
  '#295b40',
  '#59531e',
  '#125393',
  '#6d21c6',
  '#2e5954',
  '#48463f',
]

brights = [
  '#4e443d',
  '#a51010',
  '#2e5c22',
  '#794512',
  '#1f586f',
  '#6c20c8',
  '#2e5953',
  '#663c0a',
]

[colors.indexed]
16 = '#633d18'
17 = '#5b5216'

[colors.tab_bar]
background = '#f3cfba'
inactive_tab_edge = '#f0c6ad'

[colors.tab_bar.active_tab]
bg_color = '#880101'
fg_color = '#f5d8c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eebda0'
fg_color = '#880101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eebda0'
fg_color = '#8c4908'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8c4908'
fg_color = '#f5d8c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2c685f'
fg_color = '#f5d8c7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 4'