# extras/wezterm/oasis_sol_light_4.toml
## name: Oasis Sol Light 4
## author: uhs-robert

[colors]
foreground = "#64332a"
background= "#f5cdc7"
cursor_bg = "#942023"
cursor_border = "#942023"
cursor_fg= "#f5cdc7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#7c1e1e"
compose_cursor= "#543d18"
scrollbar_thumb= "#eeaaa0"
visual_bell= "#f3c1ba"

ansi = [
  '#414141',
  '#9c1010',
  '#26563d',
  '#544e1c',
  '#114e8b',
  '#671ebc',
  '#2b544f',
  '#43413a',
]

brights = [
  '#47403b',
  '#9c0f0f',
  '#2c5720',
  '#724111',
  '#1e5368',
  '#661ebd',
  '#2b544e',
  '#5f380a',
]

[colors.indexed]
16 = '#543d18'
17 = '#564e15'

[colors.tab_bar]
background = '#f3c1ba'
inactive_tab_edge = '#f0b6ad'

[colors.tab_bar.active_tab]
bg_color = '#880101'
fg_color = '#f5cdc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eeaaa0'
fg_color = '#880101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eeaaa0'
fg_color = '#8c4908'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8c4908'
fg_color = '#f5cdc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#035691'
fg_color = '#f5cdc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 4'