# extras/wezterm/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors]
foreground = "#4f4d44"
background= "#f0e9d1"
cursor_bg = "#635918"
cursor_border = "#635918"
cursor_fg= "#f0e9d1"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#504d36"
compose_cursor= "#6e431b"
scrollbar_thumb= "#e5d8ae"
visual_bell= "#ece3c5"

ansi = [
  '#4c4c4c',
  '#b21212',
  '#2c6346',
  '#605a20',
  '#135a9f',
  '#7623d6',
  '#32605b',
  '#4f4d45',
]

brights = [
  '#564b43',
  '#b21111',
  '#326425',
  '#834b13',
  '#225f78',
  '#7523d8',
  '#316159',
  '#70420b',
]

[colors.indexed]
16 = '#6e431b'
17 = '#a7292d'

[colors.tab_bar]
background = '#ece3c5'
inactive_tab_edge = '#e8deba'

[colors.tab_bar.active_tab]
bg_color = '#796e11'
fg_color = '#f0e9d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e5d8ae'
fg_color = '#796e11'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e5d8ae'
fg_color = '#2c685f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2c685f'
fg_color = '#f0e9d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#430192'
fg_color = '#f0e9d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 4'