# extras/wezterm/oasis_starlight_light_4.toml
## name: Oasis Starlight Light 4
## author: uhs-robert

[colors]
foreground = "#524b3b"
background= "#f0e6d1"
cursor_bg = "#125a97"
cursor_border = "#125a97"
cursor_fg= "#f0e6d1"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#1f4f71"
compose_cursor= "#6c411a"
scrollbar_thumb= "#e5d3ae"
visual_bell= "#ece0c5"

ansi = [
  '#4b4b4b',
  '#af1212',
  '#2b6245',
  '#5f5820',
  '#13589d',
  '#7423d3',
  '#315f5a',
  '#4e4b44',
]

brights = [
  '#544942',
  '#af1111',
  '#326224',
  '#814a13',
  '#215e76',
  '#7322d5',
  '#315f58',
  '#6e400b',
]

[colors.indexed]
16 = '#6c411a'
17 = '#af1319'

[colors.tab_bar]
background = '#ece0c5'
inactive_tab_edge = '#e8d9ba'

[colors.tab_bar.active_tab]
bg_color = '#035087'
fg_color = '#f0e6d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e5d3ae'
fg_color = '#035087'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e5d3ae'
fg_color = '#827712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#827712'
fg_color = '#f0e6d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8c4908'
fg_color = '#f0e6d1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 4'