# extras/wezterm/oasis_lagoon_light_4.toml
## name: Oasis Lagoon Light 4
## author: uhs-robert

[colors]
foreground = "#334561"
background= "#c9dcf7"
cursor_bg = "#11528a"
cursor_border = "#11528a"
cursor_fg= "#c9dcf7"
selection_bg= "#9fcae0"
selection_fg= "#0f384c"
split= "#1c4766"
compose_cursor= "#613b18"
scrollbar_thumb= "#a1c2f1"
visual_bell= "#bcd3f5"

ansi = [
  '#444444',
  '#a11010',
  '#28593f',
  '#57511d',
  '#11518f',
  '#6a20c1',
  '#2d5752',
  '#46443d',
]

brights = [
  '#4c423b',
  '#a11010',
  '#2d5a21',
  '#764312',
  '#1f566c',
  '#691fc3',
  '#2c5751',
  '#643a0a',
]

[colors.indexed]
16 = '#613b18'
17 = '#9c1b1f'

[colors.tab_bar]
background = '#bcd3f5'
inactive_tab_edge = '#aecbf3'

[colors.tab_bar.active_tab]
bg_color = '#035087'
fg_color = '#c9dcf7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#a1c2f1'
fg_color = '#035087'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#a1c2f1'
fg_color = '#8c4908'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8c4908'
fg_color = '#c9dcf7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#920101'
fg_color = '#c9dcf7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Lagoon Light 4'