# extras/wezterm/oasis_desert_light_4.toml
## name: Oasis Desert Light 4
## author: uhs-robert

[colors]
foreground = "#564634"
background= "#f5dfc7"
cursor_bg = "#5e5517"
cursor_border = "#5e5517"
cursor_fg= "#f5dfc7"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#8a2121"
compose_cursor= "#683f19"
scrollbar_thumb= "#eec9a0"
visual_bell= "#f3d8ba"

ansi = [
  '#494949',
  '#aa1111',
  '#2a5f43',
  '#5c561f',
  '#135698',
  '#7122cd',
  '#305c57',
  '#4b4941',
]

brights = [
  '#514740',
  '#aa1010',
  '#306023',
  '#7d4813',
  '#205b73',
  '#7021cf',
  '#2f5d56',
  '#6b3e0b',
]

[colors.indexed]
16 = '#683f19'
17 = '#a32124'

[colors.tab_bar]
background = '#f3d8ba'
inactive_tab_edge = '#f0d0ad'

[colors.tab_bar.active_tab]
bg_color = '#796e11'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eec9a0'
fg_color = '#796e11'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eec9a0'
fg_color = '#920101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#920101'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2c7e16'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 4'