# extras/wezterm/oasis_abyss_light_4.toml
## name: Oasis Abyss Light 4
## author: uhs-robert

[colors]
foreground = "#4e473f"
background= "#f5ddc7"
cursor_bg = "#a41c20"
cursor_border = "#a41c20"
cursor_fg= "#f5ddc7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#882121"
compose_cursor= "#673e19"
scrollbar_thumb= "#eec5a0"
visual_bell= "#f3d5ba"

ansi = [
  '#484848',
  '#a91111',
  '#2a5e42',
  '#5b551f',
  '#125597',
  '#6f21cb',
  '#2f5b56',
  '#4a4841',
]

brights = [
  '#50463f',
  '#a91010',
  '#305e23',
  '#7c4712',
  '#205a71',
  '#6f21cd',
  '#2f5c55',
  '#693e0b',
]

[colors.indexed]
16 = '#673e19'
17 = '#5b5526'

[colors.tab_bar]
background = '#f3d5ba'
inactive_tab_edge = '#f0cdad'

[colors.tab_bar.active_tab]
bg_color = '#880101'
fg_color = '#f5ddc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eec5a0'
fg_color = '#880101'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eec5a0'
fg_color = '#8c4908'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8c4908'
fg_color = '#f5ddc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2c685f'
fg_color = '#f5ddc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 4'