# extras/alacritty/themes/mirage_light_5/oasis_mirage_light_5.toml
## name: Oasis Mirage Light 5
## author: uhs-robert

[colors.primary]
background = '#c0f2ee'
foreground = '#3c5050'

[colors.selection]
background = '#9aeae4'
text = '#3c5050'

[colors.cursor]
cursor = '#605a20'
text = '#4c4c4c'

[colors.vi_mode_cursor]
cursor = '#86490d'
text = '#4c4c4c'

[colors.normal]
black   = '#4c4c4c'
red     = '#953b3b'
green   = '#2c6346'
yellow  = '#605a20'
blue    = '#1455af'
magenta = '#7622d5'
cyan    = '#32605a'
white   = '#4e4c44'

[colors.bright]
black   = '#4c4c4c'
red     = '#b11111'
green   = '#316424'
yellow  = '#86490d'
blue    = '#225f77'
magenta = '#7423d6'
cyan    = '#316159'
white   = '#70410b'