# extras/alacritty/themes/mirage_light_1/oasis_mirage_light_1.toml
## name: Oasis Mirage Light 1
## author: uhs-robert

[colors.primary]
background = '#f9fbfa'
foreground = '#455b5b'

[colors.selection]
background = '#dde9e3'
text = '#455b5b'

[colors.cursor]
cursor = '#6b6424'
text = '#575757'

[colors.vi_mode_cursor]
cursor = '#95510e'
text = '#575757'

[colors.normal]
black   = '#575757'
red     = '#a74141'
green   = '#306e4e'
yellow  = '#6b6424'
blue    = '#155fc4'
magenta = '#8234de'
cyan    = '#386c64'
white   = '#59564e'

[colors.bright]
black   = '#575757'
red     = '#c51414'
green   = '#376f28'
yellow  = '#95510e'
blue    = '#266a86'
magenta = '#8134de'
cyan    = '#366c63'
white   = '#7f4a0d'