# extras/alacritty/themes/night_light_5/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors.primary]
background = '#bcc0f5'
foreground = '#30305e'

[colors.selection]
background = '#949aef'
text = '#30305e'

[colors.cursor]
cursor = '#474217'
text = '#353535'

[colors.vi_mode_cursor]
cursor = '#63360a'
text = '#353535'

[colors.normal]
black   = '#353535'
red     = '#6f2c2c'
green   = '#204934'
yellow  = '#474217'
blue    = '#0f4083'
magenta = '#581aa0'
cyan    = '#254743'
white   = '#373530'

[colors.bright]
black   = '#353535'
red     = '#850d0d'
green   = '#254a1b'
yellow  = '#63360a'
blue    = '#194659'
magenta = '#571aa0'
cyan    = '#244742'
white   = '#4e2e08'