# extras/alacritty/themes/night_light_2/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors.primary]
background = '#e9deb9'
foreground = '#54432d'

[colors.selection]
background = '#decd96'
text = '#54432d'

[colors.cursor]
cursor = '#59531e'
text = '#464646'

[colors.vi_mode_cursor]
cursor = '#7c440c'
text = '#464646'

[colors.normal]
black   = '#464646'
red     = '#8b3636'
green   = '#295c41'
yellow  = '#59531e'
blue    = '#1250a3'
magenta = '#6d20c7'
cyan    = '#2e5955'
white   = '#48463f'

[colors.bright]
black   = '#464646'
red     = '#a51111'
green   = '#2e5c22'
yellow  = '#7c440c'
blue    = '#20586f'
magenta = '#6c21c8'
cyan    = '#2e5a53'
white   = '#673c0a'