# extras/alacritty/themes/night_light_1/oasis_night_light_1.toml
## name: Oasis Night Light 1
## author: uhs-robert

[colors.primary]
background = '#e0dbcc'
foreground = '#52422d'

[colors.selection]
background = '#cfc7af'
text = '#52422d'

[colors.cursor]
cursor = '#57511d'
text = '#444444'

[colors.vi_mode_cursor]
cursor = '#7a420c'
text = '#444444'

[colors.normal]
black   = '#444444'
red     = '#883535'
green   = '#275a3f'
yellow  = '#57511d'
blue    = '#114ea0'
magenta = '#6b20c3'
cyan    = '#2d5852'
white   = '#47443e'

[colors.bright]
black   = '#444444'
red     = '#a21010'
green   = '#2d5b20'
yellow  = '#7a420c'
blue    = '#1f566d'
magenta = '#6a20c4'
cyan    = '#2c5851'
white   = '#653b0a'