# extras/alacritty/themes/night_light_3/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors.primary]
background = '#ddddf4'
foreground = '#424175'

[colors.selection]
background = '#babae9'
text = '#424175'

[colors.cursor]
cursor = '#5a541e'
text = '#464646'

[colors.vi_mode_cursor]
cursor = '#7d440c'
text = '#464646'

[colors.normal]
black   = '#464646'
red     = '#8c3737'
green   = '#295c41'
yellow  = '#5a541e'
blue    = '#1250a4'
magenta = '#6e21c8'
cyan    = '#2f5a54'
white   = '#494640'

[colors.bright]
black   = '#464646'
red     = '#a61111'
green   = '#2f5d22'
yellow  = '#7d440c'
blue    = '#20596f'
magenta = '#6d21c9'
cyan    = '#2e5a54'
white   = '#683c0a'