# extras/alacritty/themes/night_light_1/oasis_night_light_1.toml
## name: Oasis Night Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f9fb'
foreground = '#4d4d99'

[colors.selection]
background = '#dddde9'
text = '#4d4d99'

[colors.cursor]
cursor = '#6a6323'
text = '#565656'

[colors.vi_mode_cursor]
cursor = '#94510e'
text = '#565656'

[colors.normal]
black   = '#565656'
red     = '#a64141'
green   = '#306d4d'
yellow  = '#6a6323'
blue    = '#155fc3'
magenta = '#8133dd'
cyan    = '#376b63'
white   = '#59564d'

[colors.bright]
black   = '#565656'
red     = '#c41414'
green   = '#376e28'
yellow  = '#94510e'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#7e490d'