# extras/alacritty/themes/night_light_5/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors.primary]
background = '#bcbef5'
foreground = '#313057'

[colors.selection]
background = '#9497ef'
text = '#313057'

[colors.cursor]
cursor = '#464117'
text = '#343434'

[colors.vi_mode_cursor]
cursor = '#62350a'
text = '#343434'

[colors.normal]
black   = '#343434'
red     = '#6d2b2b'
green   = '#204833'
yellow  = '#464117'
blue    = '#0f3f81'
magenta = '#57199e'
cyan    = '#244642'
white   = '#36342f'

[colors.bright]
black   = '#343434'
red     = '#840d0d'
green   = '#24491a'
yellow  = '#62350a'
blue    = '#194557'
magenta = '#561a9e'
cyan    = '#244641'
white   = '#4c2d08'