# extras/alacritty/themes/night_light_3/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors.primary]
background = '#d9d9f7'
foreground = '#3e3e79'

[colors.selection]
background = '#b3b3ef'
text = '#3e3e79'

[colors.cursor]
cursor = '#58511d'
text = '#444444'

[colors.vi_mode_cursor]
cursor = '#7a430c'
text = '#444444'

[colors.normal]
black   = '#444444'
red     = '#883636'
green   = '#285a3f'
yellow  = '#58511d'
blue    = '#114ea0'
magenta = '#6b20c3'
cyan    = '#2e5853'
white   = '#47443e'

[colors.bright]
black   = '#444444'
red     = '#a21010'
green   = '#2d5b21'
yellow  = '#7a430c'
blue    = '#1f576d'
magenta = '#6a20c5'
cyan    = '#2d5852'
white   = '#653b0a'