# extras/alacritty/themes/night_light_2/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors.primary]
background = '#ebebf9'
foreground = '#47478b'

[colors.selection]
background = '#c8c8ee'
text = '#47478b'

[colors.cursor]
cursor = '#625b21'
text = '#4e4e4e'

[colors.vi_mode_cursor]
cursor = '#894b0d'
text = '#4e4e4e'

[colors.normal]
black   = '#4e4e4e'
red     = '#993c3c'
green   = '#2d6547'
yellow  = '#625b21'
blue    = '#1358b3'
magenta = '#7823db'
cyan    = '#33635d'
white   = '#514e46'

[colors.bright]
black   = '#4e4e4e'
red     = '#b51212'
green   = '#336625'
yellow  = '#894b0d'
blue    = '#23617a'
magenta = '#7725db'
cyan    = '#32635b'
white   = '#73430b'