# extras/alacritty/themes/night_light_4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#cfcef3'
foreground = '#3b3968'

[colors.selection]
background = '#aba9ea'
text = '#3b3968'

[colors.cursor]
cursor = '#514b1b'
text = '#3e3e3e'

[colors.vi_mode_cursor]
cursor = '#703d0b'
text = '#3e3e3e'

[colors.normal]
black   = '#3e3e3e'
red     = '#7e3131'
green   = '#25533a'
yellow  = '#514b1b'
blue    = '#104893'
magenta = '#631db5'
cyan    = '#2a514c'
white   = '#403e38'

[colors.bright]
black   = '#3e3e3e'
red     = '#960f0f'
green   = '#2a531f'
yellow  = '#703d0b'
blue    = '#1c5064'
magenta = '#621db6'
cyan    = '#29514b'
white   = '#5b3509'