# extras/alacritty/themes/night_light_2/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors.primary]
background = '#ececf9'
foreground = '#4a4883'

[colors.selection]
background = '#c9c9ee'
text = '#4a4883'

[colors.cursor]
cursor = '#635c21'
text = '#4f4f4f'

[colors.vi_mode_cursor]
cursor = '#8a4b0d'
text = '#4f4f4f'

[colors.normal]
black   = '#4f4f4f'
red     = '#9a3c3c'
green   = '#2d6548'
yellow  = '#635c21'
blue    = '#1358b4'
magenta = '#7924dc'
cyan    = '#33635e'
white   = '#524f47'

[colors.bright]
black   = '#4f4f4f'
red     = '#b61212'
green   = '#336625'
yellow  = '#8a4b0d'
blue    = '#23627b'
magenta = '#7826db'
cyan    = '#33635c'
white   = '#74430b'