# extras/alacritty/themes/night_light_4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#e3d7aa'
foreground = '#4f3f2b'

[colors.selection]
background = '#d8c688'
text = '#4f3f2b'

[colors.cursor]
cursor = '#544f1c'
text = '#424242'

[colors.vi_mode_cursor]
cursor = '#76400c'
text = '#424242'

[colors.normal]
black   = '#424242'
red     = '#843434'
green   = '#27573d'
yellow  = '#544f1c'
blue    = '#114c9b'
magenta = '#681fbd'
cyan    = '#2c554f'
white   = '#44423b'

[colors.bright]
black   = '#424242'
red     = '#9d0f0f'
green   = '#2c5820'
yellow  = '#76400c'
blue    = '#1e5369'
magenta = '#671fbe'
cyan    = '#2b554e'
white   = '#60380a'