# extras/alacritty/themes/night_light_4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#c9caf7'
foreground = '#36366b'

[colors.selection]
background = '#a1a3f1'
text = '#36366b'

[colors.cursor]
cursor = '#4e491a'
text = '#3c3c3c'

[colors.vi_mode_cursor]
cursor = '#6d3b0b'
text = '#3c3c3c'

[colors.normal]
black   = '#3c3c3c'
red     = '#7a3030'
green   = '#245039'
yellow  = '#4e491a'
blue    = '#0f468f'
magenta = '#601caf'
cyan    = '#284e49'
white   = '#3d3c36'

[colors.bright]
black   = '#3c3c3c'
red     = '#920e0e'
green   = '#29511e'
yellow  = '#6d3b0b'
blue    = '#1b4d61'
magenta = '#5f1cb0'
cyan    = '#284e49'
white   = '#583309'