# extras/alacritty/themes/light/4/oasis_desert_light_4.toml
## name: Oasis Desert Light 4
## author: uhs-robert

[colors.primary]
background = '#f5dfc7'
foreground = '#564634'

[colors.selection]
background = '#eec9a0'
text = '#564634'

[colors.cursor]
cursor = '#5e5517'
text = '#f5dfc7'

[colors.vi_mode_cursor]
cursor = '#7d4813'
text = '#f5dfc7'

[colors.normal]
black   = '#494949'
red     = '#aa1111'
green   = '#2a5f43'
yellow  = '#5c561f'
blue    = '#135698'
magenta = '#7122cd'
cyan    = '#305c57'
white   = '#4b4941'

[colors.bright]
black   = '#514740'
red     = '#aa1010'
green   = '#306023'
yellow  = '#7d4813'
blue    = '#205b73'
magenta = '#7021cf'
cyan    = '#2f5d56'
white   = '#6b3e0b'