# extras/alacritty/themes/light/4/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors.primary]
background = '#e3d7aa'
foreground = '#4f3f2b'

[colors.selection]
background = '#d8c688'
text = '#4f3f2b'

[colors.cursor]
cursor = '#773f0d'
text = '#e3d7aa'

[colors.vi_mode_cursor]
cursor = '#734211'
text = '#e3d7aa'

[colors.normal]
black   = '#5f3913'
red     = '#9d1010'
green   = '#27573d'
yellow  = '#544f1c'
blue    = '#114f8c'
magenta = '#681fbd'
cyan    = '#2c5550'
white   = '#44423b'

[colors.bright]
black   = '#533d2e'
red     = '#9d0f0f'
green   = '#2c5820'
yellow  = '#734211'
blue    = '#1e5369'
magenta = '#671fbe'
cyan    = '#2b554e'
white   = '#60380a'