# extras/alacritty/themes/light/4/oasis_sol_light_4.toml
## name: Oasis Sol Light 4
## author: uhs-robert

[colors.primary]
background = '#f5cdc7'
foreground = '#64332a'

[colors.selection]
background = '#eeaaa0'
text = '#64332a'

[colors.cursor]
cursor = '#942023'
text = '#f5cdc7'

[colors.vi_mode_cursor]
cursor = '#724111'
text = '#f5cdc7'

[colors.normal]
black   = '#414141'
red     = '#9c1010'
green   = '#26563d'
yellow  = '#544e1c'
blue    = '#114e8b'
magenta = '#671ebc'
cyan    = '#2b544f'
white   = '#43413a'

[colors.bright]
black   = '#47403b'
red     = '#9c0f0f'
green   = '#2c5720'
yellow  = '#724111'
blue    = '#1e5368'
magenta = '#661ebd'
cyan    = '#2b544e'
white   = '#5f380a'