# extras/alacritty/themes/light/4/oasis_twilight_light_4.toml
## name: Oasis Twilight Light 4
## author: uhs-robert

[colors.primary]
background = '#d7cef3'
foreground = '#433a5c'

[colors.selection]
background = '#b9a9ea'
text = '#433a5c'

[colors.cursor]
cursor = '#6914ba'
text = '#d7cef3'

[colors.vi_mode_cursor]
cursor = '#6f4011'
text = '#d7cef3'

[colors.normal]
black   = '#3f3f3f'
red     = '#980f0f'
green   = '#25543b'
yellow  = '#524c1b'
blue    = '#104c87'
magenta = '#641eb7'
cyan    = '#2a524e'
white   = '#413f39'

[colors.bright]
black   = '#473e37'
red     = '#990f0f'
green   = '#2b551f'
yellow  = '#6f4011'
blue    = '#1d5166'
magenta = '#641eb8'
cyan    = '#2a524c'
white   = '#5d3609'