# extras/alacritty/themes/light/4/oasis_rose_light_4.toml
## name: Oasis Rose Light 4
## author: uhs-robert

[colors.primary]
background = '#f3ceea'
foreground = '#513d4b'

[colors.selection]
background = '#eaa9da'
text = '#513d4b'

[colors.cursor]
cursor = '#9f1116'
text = '#f3ceea'

[colors.vi_mode_cursor]
cursor = '#754311'
text = '#f3ceea'

[colors.normal]
black   = '#434343'
red     = '#9f1010'
green   = '#27583e'
yellow  = '#56501d'
blue    = '#11508e'
magenta = '#6920bf'
cyan    = '#2d5651'
white   = '#45433c'

[colors.bright]
black   = '#4b413a'
red     = '#9f0f0f'
green   = '#2d5921'
yellow  = '#754311'
blue    = '#1e556a'
magenta = '#681fc1'
cyan    = '#2c5650'
white   = '#62390a'