# extras/alacritty/themes/light/4/oasis_mirage_light_4.toml
## name: Oasis Mirage Light 4
## author: uhs-robert

[colors.primary]
background = '#cdf4f4'
foreground = '#3e5252'

[colors.selection]
background = '#a7ecec'
text = '#3e5252'

[colors.cursor]
cursor = '#625c21'
text = '#4f4f4f'

[colors.vi_mode_cursor]
cursor = '#894b0e'
text = '#4f4f4f'

[colors.normal]
black   = '#4f4f4f'
red     = '#993c3c'
green   = '#2d6548'
yellow  = '#625c21'
blue    = '#1358b4'
magenta = '#7824db'
cyan    = '#33635c'
white   = '#514f47'

[colors.bright]
black   = '#4f4f4f'
red     = '#b61212'
green   = '#336625'
yellow  = '#894b0e'
blue    = '#23617a'
magenta = '#7724dc'
cyan    = '#33635c'
white   = '#73430c'