# extras/alacritty/themes/light/4/oasis_mirage_light_4.toml
## name: Oasis Mirage Light 4
## author: uhs-robert

[colors.primary]
background = '#cdf4f4'
foreground = '#3e5252'

[colors.selection]
background = '#a7ecec'
text = '#3e5252'

[colors.cursor]
cursor = '#31635c'
text = '#cdf4f4'

[colors.vi_mode_cursor]
cursor = '#864d14'
text = '#cdf4f4'

[colors.normal]
black   = '#4f4f4f'
red     = '#ac2727'
green   = '#2d6548'
yellow  = '#635c1e'
blue    = '#145ca3'
magenta = '#7824db'
cyan    = '#33635c'
white   = '#514f47'

[colors.bright]
black   = '#564d48'
red     = '#b61212'
green   = '#336625'
yellow  = '#864d14'
blue    = '#23617a'
magenta = '#7724dc'
cyan    = '#33635c'
white   = '#73430c'