# extras/alacritty/themes/light/4/oasis_cactus_light_4.toml
## name: Oasis Cactus Light 4
## author: uhs-robert

[colors.primary]
background = '#d6f0e1'
foreground = '#405147'

[colors.selection]
background = '#b4e4c8'
text = '#405147'

[colors.cursor]
cursor = '#3a623c'
text = '#d6f0e1'

[colors.vi_mode_cursor]
cursor = '#844b14'
text = '#d6f0e1'

[colors.normal]
black   = '#4d4d4d'
red     = '#a92626'
green   = '#2c6446'
yellow  = '#615a1e'
blue    = '#145aa0'
magenta = '#7623d8'
cyan    = '#32615b'
white   = '#504d45'

[colors.bright]
black   = '#544b46'
red     = '#b31111'
green   = '#326425'
yellow  = '#844b14'
blue    = '#226078'
magenta = '#7523d9'
cyan    = '#32615a'
white   = '#71420b'