# extras/alacritty/themes/light/4/oasis_starlight_light_4.toml
## name: Oasis Starlight Light 4
## author: uhs-robert

[colors.primary]
background = '#f0e6d1'
foreground = '#524b3b'

[colors.selection]
background = '#e5d3ae'
text = '#524b3b'

[colors.cursor]
cursor = '#5f5820'
text = '#4b4b4b'

[colors.vi_mode_cursor]
cursor = '#84480d'
text = '#4b4b4b'

[colors.normal]
black   = '#4b4b4b'
red     = '#943a3a'
green   = '#2b6245'
yellow  = '#5f5820'
blue    = '#1355ad'
magenta = '#7422d4'
cyan    = '#315f59'
white   = '#4e4b44'

[colors.bright]
black   = '#4b4b4b'
red     = '#af1111'
green   = '#326224'
yellow  = '#84480d'
blue    = '#215e76'
magenta = '#7322d5'
cyan    = '#315f58'
white   = '#6e400b'