# extras/alacritty/themes/light/4/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors.primary]
background = '#f0e9d1'
foreground = '#4f4d44'

[colors.selection]
background = '#e5d8ae'
text = '#4f4d44'

[colors.cursor]
cursor = '#635918'
text = '#f0e9d1'

[colors.vi_mode_cursor]
cursor = '#834b13'
text = '#f0e9d1'

[colors.normal]
black   = '#4c4c4c'
red     = '#b21212'
green   = '#2c6346'
yellow  = '#605a20'
blue    = '#13599f'
magenta = '#7623d7'
cyan    = '#32615a'
white   = '#4f4d45'

[colors.bright]
black   = '#544b46'
red     = '#b21111'
green   = '#326425'
yellow  = '#834b13'
blue    = '#225f78'
magenta = '#7523d8'
cyan    = '#316159'
white   = '#70420b'