# extras/alacritty/themes/light/4/oasis_abyss_light_4.toml
## name: Oasis Abyss Light 4
## author: uhs-robert

[colors.primary]
background = '#f5ddc7'
foreground = '#4e473f'

[colors.selection]
background = '#eec5a0'
text = '#4e473f'

[colors.cursor]
cursor = '#a41c20'
text = '#f5ddc7'

[colors.vi_mode_cursor]
cursor = '#7c4712'
text = '#f5ddc7'

[colors.normal]
black   = '#484848'
red     = '#a91111'
green   = '#2a5e42'
yellow  = '#5b551f'
blue    = '#125597'
magenta = '#6f21cb'
cyan    = '#2f5b56'
white   = '#4a4841'

[colors.bright]
black   = '#50463f'
red     = '#a91010'
green   = '#305e23'
yellow  = '#7c4712'
blue    = '#205a71'
magenta = '#6f21cd'
cyan    = '#2f5c55'
white   = '#693e0b'