# extras/alacritty/themes/light/4/oasis_midnight_light_4.toml
## name: Oasis Midnight Light 4
## author: uhs-robert

[colors.primary]
background = '#f5d8c7'
foreground = '#4d443e'

[colors.selection]
background = '#eebda0'
text = '#4d443e'

[colors.cursor]
cursor = '#9e2023'
text = '#f5d8c7'

[colors.vi_mode_cursor]
cursor = '#794512'
text = '#f5d8c7'

[colors.normal]
black   = '#464646'
red     = '#a51111'
green   = '#295b40'
yellow  = '#59531e'
blue    = '#125393'
magenta = '#6d20c6'
cyan    = '#2e5953'
white   = '#48463f'

[colors.bright]
black   = '#4c4440'
red     = '#a51010'
green   = '#2e5c22'
yellow  = '#794512'
blue    = '#1f586f'
magenta = '#6c20c8'
cyan    = '#2e5953'
white   = '#663c0a'