# extras/alacritty/themes/light/4/oasis_lagoon_light_4.toml
## name: Oasis Lagoon Light 4
## author: uhs-robert

[colors.primary]
background = '#c9dcf7'
foreground = '#334561'

[colors.selection]
background = '#a1c2f1'
text = '#334561'

[colors.cursor]
cursor = '#11528a'
text = '#c9dcf7'

[colors.vi_mode_cursor]
cursor = '#764312'
text = '#c9dcf7'

[colors.normal]
black   = '#444444'
red     = '#a11010'
green   = '#28593f'
yellow  = '#57511d'
blue    = '#11518f'
magenta = '#6a20c1'
cyan    = '#2d5752'
white   = '#46443d'

[colors.bright]
black   = '#4a423e'
red     = '#a11010'
green   = '#2d5a21'
yellow  = '#764312'
blue    = '#1f566c'
magenta = '#691fc3'
cyan    = '#2c5751'
white   = '#643a0a'