# extras/wezterm/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors]
foreground = "#5f514e"
background= "#f9f5f5"
cursor_bg= "#ba2328"
cursor_border= "#ba2328"
cursor_fg= "#f3ebeb"
selection_bg= "#e8d8d8"
selection_fg= "#f3ebeb"
split= "#804242"
compose_cursor= "#79481c"
scrollbar_thumb= "#e8d8d8"
visual_bell= "#f3ebeb"

ansi = [
  '#545454',
  '#a33f3f',
  '#2f6b4c',
  '#686223',
  '#155dbf',
  '#7f2fdd',
  '#366961',
  '#57544c',
]

brights = [
  '#545454',
  '#c01313',
  '#366c27',
  '#914f0e',
  '#256782',
  '#7e2fdd',
  '#356961',
  '#7b480c',
]

[colors.indexed]
16 = '#79481c'
17 = '#67612e'

[colors.tab_bar]
background = '#f3ebeb'
inactive_tab_edge = '#eee2e2'

[colors.tab_bar.active_tab]
bg_color = '#7d2b2b'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8d8d8'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f3ebeb'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#ab5807'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e756c'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 1'