# extras/wezterm/oasis_abyss_light_2.toml
## name: Oasis Abyss Light 2
## author: uhs-robert

[colors]
foreground = "#5a4c4a"
background= "#f8ebe7"
cursor_bg= "#b02227"
cursor_border= "#b02227"
cursor_fg= "#f5e1db"
selection_bg= "#eecdc3"
selection_fg= "#f5e1db"
split= "#7a3e3e"
compose_cursor= "#72441b"
scrollbar_thumb= "#eecdc3"
visual_bell= "#f5e1db"

ansi = [
  '#4f4f4f',
  '#9b3d3d',
  '#2e6648',
  '#635d21',
  '#1459b5',
  '#7925dc',
  '#33645e',
  '#524f47',
]

brights = [
  '#4f4f4f',
  '#b71212',
  '#336725',
  '#8a4b0d',
  '#23627b',
  '#7827db',
  '#33645c',
  '#74440b',
]

[colors.indexed]
16 = '#72441b'
17 = '#625d2d'

[colors.tab_bar]
background = '#f5e1db'
inactive_tab_edge = '#f1d7cf'

[colors.tab_bar.active_tab]
bg_color = '#762828'
fg_color = '#f8ebe7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eecdc3'
fg_color = '#f8ebe7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f5e1db'
fg_color = '#f8ebe7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a35305'
fg_color = '#f8ebe7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3a6f66'
fg_color = '#f8ebe7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 2'