# extras/alacritty/themes/starlight_light_5/oasis_starlight_light_5.toml
## name: Oasis Starlight Light 5
## author: uhs-robert

[colors.primary]
background = '#f3deba'
foreground = '#4d4738'

[colors.selection]
background = '#eccb93'
text = '#4d4738'

[colors.cursor]
cursor = '#5b551e'
text = '#474747'

[colors.vi_mode_cursor]
cursor = '#7e450d'
text = '#474747'

[colors.normal]
black   = '#474747'
red     = '#8d3838'
green   = '#2a5d42'
yellow  = '#5b551e'
blue    = '#1351a6'
magenta = '#7021ca'
cyan    = '#2f5b55'
white   = '#4a4740'

[colors.bright]
black   = '#474747'
red     = '#a81010'
green   = '#2f5e22'
yellow  = '#7e450d'
blue    = '#205a71'
magenta = '#6e21cb'
cyan    = '#2e5b54'
white   = '#693d0b'