# extras/alacritty/themes/starlight_light_3/oasis_starlight_light_3.toml
## name: Oasis Starlight Light 3
## author: uhs-robert

[colors.primary]
background = '#f4eddd'
foreground = '#564f3e'

[colors.selection]
background = '#e9dbba'
text = '#564f3e'

[colors.cursor]
cursor = '#645d21'
text = '#4f4f4f'

[colors.vi_mode_cursor]
cursor = '#8a4b0e'
text = '#4f4f4f'

[colors.normal]
black   = '#4f4f4f'
red     = '#9a3d3d'
green   = '#2e6648'
yellow  = '#645d21'
blue    = '#1458b5'
magenta = '#7925db'
cyan    = '#34635d'
white   = '#524f47'

[colors.bright]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#336725'
yellow  = '#8a4b0e'
blue    = '#23627b'
magenta = '#7826dc'
cyan    = '#33645d'
white   = '#74440b'