# extras/wezterm/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors]
foreground = "#5c534b"
background= "#f9f7f5"
cursor_bg = "#bb2328"
cursor_border = "#bb2328"
cursor_fg= "#f9f7f5"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#943434"
compose_cursor= "#7a491d"
scrollbar_thumb= "#e8e0d8"
visual_bell= "#f3efeb"

ansi = [
  '#555555',
  '#b72a2a',
  '#306c4c',
  '#696220',
  '#1662ae',
  '#7f30dd',
  '#376a62',
  '#58554c',
]

brights = [
  '#5c534d',
  '#c21313',
  '#366d27',
  '#8f5215',
  '#266884',
  '#7f31de',
  '#356a62',
  '#7d490c',
]

[colors.indexed]
16 = '#7a491d'
17 = '#68622f'

[colors.tab_bar]
background = '#f3efeb'
inactive_tab_edge = '#eee8e2'

[colors.tab_bar.active_tab]
bg_color = '#8f1919'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8e0d8'
fg_color = '#8f1919'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e0d8'
fg_color = '#a4590f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a4590f'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e756c'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 1'