# extras/wezterm/oasis_rose_light_1.toml
## name: Oasis Rose Light 1
## author: uhs-robert

[colors]
foreground = "#694e63"
background= "#fbf9fb"
cursor_bg = "#c3151c"
cursor_border = "#c3151c"
cursor_fg= "#fbf9fb"
selection_bg= "#dba3c6"
selection_fg= "#481335"
split= "#a32626"
compose_cursor= "#7c4b1d"
scrollbar_thumb= "#e9dde9"
visual_bell= "#f5f0f5"

ansi = [
  '#565656',
  '#c41414',
  '#306e4d',
  '#6a6423',
  '#1663b1',
  '#8132de',
  '#376b65',
  '#59564d',
]

brights = [
  '#60544a',
  '#c41414',
  '#376f28',
  '#915315',
  '#266985',
  '#8033de',
  '#366b63',
  '#7e4a0d',
]

[colors.indexed]
16 = '#7c4b1d'
17 = '#6b632c'

[colors.tab_bar]
background = '#f5f0f5'
inactive_tab_edge = '#efe7ef'

[colors.tab_bar.active_tab]
bg_color = '#a20707'
fg_color = '#fbf9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9dde9'
fg_color = '#a20707'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9dde9'
fg_color = '#3e7540'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#3e7540'
fg_color = '#fbf9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#377c71'
fg_color = '#fbf9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Light 1'