# extras/wezterm/oasis_sol_light_1.toml
## name: Oasis Sol Light 1
## author: uhs-robert

[colors]
foreground = "#814236"
background= "#f9f5f5"
cursor_bg = "#b6282c"
cursor_border = "#b6282c"
cursor_fg= "#f9f5f5"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#8b3a3a"
compose_cursor= "#6c4f1f"
scrollbar_thumb= "#e8d8d8"
visual_bell= "#f3ebeb"

ansi = [
  '#545454',
  '#a33f3f',
  '#2f6b4c',
  '#686223',
  '#155dbf',
  '#7f2fdd',
  '#366961',
  '#57544c',
]

brights = [
  '#5b534c',
  '#c01313',
  '#366c27',
  '#8e5115',
  '#256782',
  '#7e2fdd',
  '#356961',
  '#7b480c',
]

[colors.indexed]
16 = '#6c4f1f'
17 = '#6c6119'

[colors.tab_bar]
background = '#f3ebeb'
inactive_tab_edge = '#eee2e2'

[colors.tab_bar.active_tab]
bg_color = '#8f1919'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8d8d8'
fg_color = '#8f1919'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8d8d8'
fg_color = '#a4590f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a4590f'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#0966a9'
fg_color = '#f9f5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 1'