# extras/wezterm/oasis_starlight_light_1.toml
## name: Oasis Starlight Light 1
## author: uhs-robert

[colors]
foreground = "#5c5442"
background= "#f9f7f5"
cursor_bg = "#1563a7"
cursor_border = "#1563a7"
cursor_fg= "#f9f7f5"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#23597f"
compose_cursor= "#794a1c"
scrollbar_thumb= "#e8e0d8"
visual_bell= "#f3efeb"

ansi = [
  '#555555',
  '#b72a2a',
  '#306c4c',
  '#696220',
  '#1662ae',
  '#7f30dd',
  '#376a62',
  '#58554c',
]

brights = [
  '#5c534d',
  '#c21313',
  '#366d27',
  '#8f5215',
  '#266884',
  '#7f31de',
  '#356a62',
  '#7d490c',
]

[colors.indexed]
16 = '#794a1c'
17 = '#b62c30'

[colors.tab_bar]
background = '#f3efeb'
inactive_tab_edge = '#eee8e2'

[colors.tab_bar.active_tab]
bg_color = '#0961a0'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8e0d8'
fg_color = '#0961a0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e0d8'
fg_color = '#988c1a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#988c1a'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#a4590f'
fg_color = '#f9f7f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 1'