# extras/wezterm/oasis_twilight_light_1.toml
## name: Oasis Twilight Light 1
## author: uhs-robert

[colors]
foreground = "#5b4f7e"
background= "#f9f9fb"
cursor_bg = "#8724e7"
cursor_border = "#8724e7"
cursor_fg= "#f9f9fb"
selection_bg= "#c3a1dd"
selection_fg= "#31124a"
split= "#6a3fa2"
compose_cursor= "#7a4b1d"
scrollbar_thumb= "#dddde9"
visual_bell= "#f0f0f5"

ansi = [
  '#565656',
  '#a64141',
  '#306d4d',
  '#6a6323',
  '#155fc3',
  '#8133dd',
  '#376b63',
  '#59564d',
]

brights = [
  '#5d544e',
  '#c41414',
  '#376e28',
  '#905315',
  '#266985',
  '#8033de',
  '#366b63',
  '#7e490d',
]

[colors.indexed]
16 = '#7a4b1d'
17 = '#ba292e'

[colors.tab_bar]
background = '#f0f0f5'
inactive_tab_edge = '#e7e7ef'

[colors.tab_bar.active_tab]
bg_color = '#4e07a2'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dddde9'
fg_color = '#4e07a2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dddde9'
fg_color = '#998b19'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#998b19'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#298a58'
fg_color = '#f9f9fb'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Light 1'