# extras/wezterm/oasis_mirage_light_1.toml
## name: Oasis Mirage Light 1
## author: uhs-robert

[colors]
foreground = "#455b5b"
background= "#f9fbfa"
cursor_bg = "#356c63"
cursor_border = "#356c63"
cursor_fg= "#f9fbfa"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#395d58"
compose_cursor= "#7b4b1d"
scrollbar_thumb= "#dde9e3"
visual_bell= "#f0f5f2"

ansi = [
  '#575757',
  '#a74141',
  '#306e4e',
  '#6b6424',
  '#155fc4',
  '#8234de',
  '#386c64',
  '#59564e',
]

brights = [
  '#5e554f',
  '#c51414',
  '#376f28',
  '#925416',
  '#266a86',
  '#8134de',
  '#366c63',
  '#7f4a0d',
]

[colors.indexed]
16 = '#7b4b1d'
17 = '#bb292d'

[colors.tab_bar]
background = '#f0f5f2'
inactive_tab_edge = '#e7efeb'

[colors.tab_bar.active_tab]
bg_color = '#3a6e66'
fg_color = '#f9fbfa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#dde9e3'
fg_color = '#3a6e66'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#dde9e3'
fg_color = '#a4590f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a4590f'
fg_color = '#f9fbfa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#5307ab'
fg_color = '#f9fbfa'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 1'