# extras/wezterm/oasis_dune_light_1.toml
## name: Oasis Dune Light 1
## author: uhs-robert

[colors]
foreground = "#58554c"
background= "#f9f8f5"
cursor_bg = "#6d6219"
cursor_border = "#6d6219"
cursor_fg= "#f9f8f5"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#58563c"
compose_cursor= "#7a4a1d"
scrollbar_thumb= "#e8e4d8"
visual_bell= "#f3f1eb"

ansi = [
  '#555555',
  '#c21313',
  '#306d4d',
  '#696323',
  '#1662b0',
  '#8031de',
  '#366a65',
  '#58554d',
]

brights = [
  '#5f5349',
  '#c21414',
  '#366e27',
  '#905215',
  '#266884',
  '#7f32de',
  '#366a62',
  '#7d490c',
]

[colors.indexed]
16 = '#7a4a1d'
17 = '#b72b30'

[colors.tab_bar]
background = '#f3f1eb'
inactive_tab_edge = '#eeebe2'

[colors.tab_bar.active_tab]
bg_color = '#908419'
fg_color = '#f9f8f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e8e4d8'
fg_color = '#908419'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e4d8'
fg_color = '#377c72'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#377c72'
fg_color = '#f9f8f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#5107ab'
fg_color = '#f9f8f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 1'