# extras/alacritty/themes/dusk/oasis_dusk.toml
## name: Oasis Dusk
## author: uhs-robert

[colors.primary]
background = '#DCBA75'
foreground = '#251C10'

[colors.selection]
background = '#CEAC5F'
text = '#251C10'

[colors.cursor]
cursor = '#433f17'
text = '#313131'

[colors.vi_mode_cursor]
cursor = '#5d3309'
text = '#313131'

[colors.normal]
black   = '#313131'
red     = '#692929'
green   = '#1f4530'
yellow  = '#433f17'
blue    = '#0d3c7b'
magenta = '#531998'
cyan    = '#234340'
white   = '#33312c'

[colors.bright]
black   = '#313131'
red     = '#7e0d0d'
green   = '#234519'
yellow  = '#5d3309'
blue    = '#184254'
magenta = '#521998'
cyan    = '#22433e'
white   = '#492a07'