# extras/wezterm/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors]
foreground = "#313057"
background= "#bcbef5"
cursor_bg= "#7e191c"
cursor_border= "#7e191c"
cursor_fg= "#afb1f3"
selection_bg= "#9497ef"
selection_fg= "#afb1f3"
split= "#502929"
compose_cursor= "#4a2e12"
scrollbar_thumb= "#9497ef"
visual_bell= "#afb1f3"

ansi = [
  '#343434',
  '#6d2b2b',
  '#204833',
  '#464117',
  '#0f3f81',
  '#57199e',
  '#244642',
  '#36342f',
]

brights = [
  '#343434',
  '#840d0d',
  '#24491a',
  '#62350a',
  '#194557',
  '#561a9e',
  '#244641',
  '#4c2d08',
]

[colors.indexed]
16 = '#4a2e12'
17 = '#484111'

[colors.tab_bar]
background = '#afb1f3'
inactive_tab_edge = '#a1a4f1'

[colors.tab_bar.active_tab]
bg_color = '#621e1e'
fg_color = '#bcbef5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#9497ef'
fg_color = '#bcbef5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#afb1f3'
fg_color = '#bcbef5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8a4400'
fg_color = '#bcbef5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#025088'
fg_color = '#bcbef5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 5'