# extras/wezterm/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors]
foreground = "#3e3e79"
background= "#d9d9f7"
cursor_bg= "#9c1e23"
cursor_border= "#9c1e23"
cursor_fg= "#ccccf4"
selection_bg= "#b3b3ef"
selection_fg= "#ccccf4"
split= "#693636"
compose_cursor= "#613c18"
scrollbar_thumb= "#b3b3ef"
visual_bell= "#ccccf4"

ansi = [
  '#444444',
  '#883636',
  '#285a3f',
  '#58511d',
  '#114ea0',
  '#6b20c3',
  '#2e5853',
  '#47443e',
]

brights = [
  '#444444',
  '#a21010',
  '#2d5b21',
  '#7a430c',
  '#1f576d',
  '#6a20c5',
  '#2d5852',
  '#653b0a',
]

[colors.indexed]
16 = '#613c18'
17 = '#5b5116'

[colors.tab_bar]
background = '#ccccf4'
inactive_tab_edge = '#c0c0f2'

[colors.tab_bar.active_tab]
bg_color = '#702424'
fg_color = '#d9d9f7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b3b3ef'
fg_color = '#d9d9f7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ccccf4'
fg_color = '#d9d9f7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9b4e03'
fg_color = '#d9d9f7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#055b99'
fg_color = '#d9d9f7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 3'