# extras/wezterm/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors]
foreground = "#30305e"
background= "#bcc0f5"
cursor_bg= "#80191c"
cursor_border= "#80191c"
cursor_fg= "#afb3f3"
selection_bg= "#949aef"
selection_fg= "#afb3f3"
split= "#512a2a"
compose_cursor= "#4c2f12"
scrollbar_thumb= "#949aef"
visual_bell= "#afb3f3"

ansi = [
  '#353535',
  '#6f2c2c',
  '#204934',
  '#474217',
  '#0f4083',
  '#581aa0',
  '#254743',
  '#373530',
]

brights = [
  '#353535',
  '#850d0d',
  '#254a1b',
  '#63360a',
  '#194659',
  '#571aa0',
  '#244742',
  '#4e2e08',
]

[colors.indexed]
16 = '#4c2f12'
17 = '#494212'

[colors.tab_bar]
background = '#afb3f3'
inactive_tab_edge = '#a1a7f1'

[colors.tab_bar.active_tab]
bg_color = '#621e1e'
fg_color = '#bcc0f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#949aef'
fg_color = '#bcc0f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#afb3f3'
fg_color = '#bcc0f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8a4400'
fg_color = '#bcc0f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#025088'
fg_color = '#bcc0f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 5'