# extras/wezterm/oasis_night_light_4.toml
## name: Oasis Night Light 4
## author: uhs-robert

[colors]
foreground = "#3b3968"
background= "#cfcef3"
cursor_bg= "#901d20"
cursor_border= "#901d20"
cursor_fg= "#c3c2f0"
selection_bg= "#aba9ea"
selection_fg= "#c3c2f0"
split= "#603030"
compose_cursor= "#593715"
scrollbar_thumb= "#aba9ea"
visual_bell= "#c3c2f0"

ansi = [
  '#3e3e3e',
  '#7e3131',
  '#25533a',
  '#514b1b',
  '#104893',
  '#631db5',
  '#2a514c',
  '#403e38',
]

brights = [
  '#3e3e3e',
  '#960f0f',
  '#2a531f',
  '#703d0b',
  '#1c5064',
  '#621db6',
  '#29514b',
  '#5b3509',
]

[colors.indexed]
16 = '#593715'
17 = '#534b14'

[colors.tab_bar]
background = '#c3c2f0'
inactive_tab_edge = '#b7b5ed'

[colors.tab_bar.active_tab]
bg_color = '#692121'
fg_color = '#cfcef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#aba9ea'
fg_color = '#cfcef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c3c2f0'
fg_color = '#cfcef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#924901'
fg_color = '#cfcef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#035691'
fg_color = '#cfcef3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 4'