# extras/wezterm/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors]
foreground = "#4a4883"
background= "#ececf9"
cursor_bg= "#b02227"
cursor_border= "#b02227"
cursor_fg= "#e0e0f5"
selection_bg= "#c9c9ee"
selection_fg= "#e0e0f5"
split= "#793d3d"
compose_cursor= "#70451a"
scrollbar_thumb= "#c9c9ee"
visual_bell= "#e0e0f5"

ansi = [
  '#4f4f4f',
  '#9a3c3c',
  '#2d6548',
  '#635c21',
  '#1358b4',
  '#7924dc',
  '#33635e',
  '#524f47',
]

brights = [
  '#4f4f4f',
  '#b61212',
  '#336625',
  '#8a4b0d',
  '#23627b',
  '#7826db',
  '#33635c',
  '#74430b',
]

[colors.indexed]
16 = '#70451a'
17 = '#665c19'

[colors.tab_bar]
background = '#e0e0f5'
inactive_tab_edge = '#d5d5f2'

[colors.tab_bar.active_tab]
bg_color = '#762828'
fg_color = '#ececf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c9c9ee'
fg_color = '#ececf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e0e0f5'
fg_color = '#ececf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a35305'
fg_color = '#ececf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#0761a1'
fg_color = '#ececf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 2'