# extras/wezterm/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors]
foreground = "#424175"
background= "#ddddf4"
cursor_bg= "#a01f24"
cursor_border= "#a01f24"
cursor_fg= "#d1d1f0"
selection_bg= "#babae9"
selection_fg= "#d1d1f0"
split= "#6c3737"
compose_cursor= "#643e18"
scrollbar_thumb= "#babae9"
visual_bell= "#d1d1f0"

ansi = [
  '#464646',
  '#8c3737',
  '#295c41',
  '#5a541e',
  '#1250a4',
  '#6e21c8',
  '#2f5a54',
  '#494640',
]

brights = [
  '#464646',
  '#a61111',
  '#2f5d22',
  '#7d440c',
  '#20596f',
  '#6d21c9',
  '#2e5a54',
  '#683c0a',
]

[colors.indexed]
16 = '#643e18'
17 = '#5d5316'

[colors.tab_bar]
background = '#d1d1f0'
inactive_tab_edge = '#c6c6ed'

[colors.tab_bar.active_tab]
bg_color = '#702424'
fg_color = '#ddddf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#babae9'
fg_color = '#ddddf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d1d1f0'
fg_color = '#ddddf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9b4e03'
fg_color = '#ddddf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#055b99'
fg_color = '#ddddf4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 3'