# extras/alacritty/themes/lagoon_dark/oasis_lagoon_dark.toml
## name: Oasis Lagoon Dark
## author: uhs-robert

[colors.primary]
background = '#101825'
foreground = '#D9E6FA'

[colors.selection]
background = '#5A3824'
text = '#D9E6FA'

[colors.cursor]
cursor = '#F0E68C'
text = '#000000'

[colors.vi_mode_cursor]
cursor = '#FFA247'
text = '#000000'

[colors.normal]
black   = '#000000'
red     = '#D06666'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#519BFF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#666666'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#FFA247'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'