# extras/alacritty/themes/lagoon_light_1/oasis_lagoon_light_1.toml
## name: Oasis Lagoon Light 1
## author: uhs-robert

[colors.primary]
background = '#f9fafb'
foreground = '#40577a'

[colors.selection]
background = '#dde3e9'
text = '#40577a'

[colors.cursor]
cursor = '#6a6423'
text = '#565656'

[colors.vi_mode_cursor]
cursor = '#95510e'
text = '#565656'

[colors.normal]
black   = '#565656'
red     = '#a74141'
green   = '#306e4e'
yellow  = '#6a6423'
blue    = '#155fc4'
magenta = '#8133dd'
cyan    = '#386b64'
white   = '#59564e'

[colors.bright]
black   = '#565656'
red     = '#c41414'
green   = '#376f28'
yellow  = '#95510e'
blue    = '#266a86'
magenta = '#8033de'
cyan    = '#366c63'
white   = '#7e4a0d'