# extras/alacritty/themes/twilight_light_5/oasis_twilight_light_5.toml
## name: Oasis Twilight Light 5
## author: uhs-robert

[colors.primary]
background = '#cac2f0'
foreground = '#3b3351'

[colors.selection]
background = '#aa9de7'
text = '#3b3351'

[colors.cursor]
cursor = '#4a4518'
text = '#383838'

[colors.vi_mode_cursor]
cursor = '#67380a'
text = '#383838'

[colors.normal]
black   = '#383838'
red     = '#732d2d'
green   = '#224c36'
yellow  = '#4a4518'
blue    = '#0f4288'
magenta = '#5c1ba6'
cyan    = '#264a46'
white   = '#393832'

[colors.bright]
black   = '#383838'
red     = '#8a0d0d'
green   = '#264d1c'
yellow  = '#67380a'
blue    = '#1a495c'
magenta = '#5a1ba6'
cyan    = '#264a45'
white   = '#523008'