# extras/alacritty/themes/twilight_light_4/oasis_twilight_light_4.toml
## name: Oasis Twilight Light 4
## author: uhs-robert

[colors.primary]
background = '#d7cef3'
foreground = '#433a5c'

[colors.selection]
background = '#b9a9ea'
text = '#433a5c'

[colors.cursor]
cursor = '#524c1b'
text = '#3f3f3f'

[colors.vi_mode_cursor]
cursor = '#723e0b'
text = '#3f3f3f'

[colors.normal]
black   = '#3f3f3f'
red     = '#803232'
green   = '#25543b'
yellow  = '#524c1b'
blue    = '#104996'
magenta = '#651eb7'
cyan    = '#2a524d'
white   = '#413f39'

[colors.bright]
black   = '#3f3f3f'
red     = '#990f0f'
green   = '#2b551f'
yellow  = '#723e0b'
blue    = '#1d5166'
magenta = '#641eb8'
cyan    = '#2a524c'
white   = '#5d3609'