# extras/alacritty/themes/twilight_light_3/oasis_twilight_light_3.toml
## name: Oasis Twilight Light 3
## author: uhs-robert

[colors.primary]
background = '#e2ddf4'
foreground = '#4a4268'

[colors.selection]
background = '#c4bae9'
text = '#4a4268'

[colors.cursor]
cursor = '#5b541e'
text = '#474747'

[colors.vi_mode_cursor]
cursor = '#7e450c'
text = '#474747'

[colors.normal]
black   = '#474747'
red     = '#8d3737'
green   = '#2a5d42'
yellow  = '#5b541e'
blue    = '#1251a5'
magenta = '#6f21ca'
cyan    = '#2f5b55'
white   = '#4a4740'

[colors.bright]
black   = '#474747'
red     = '#a71111'
green   = '#2f5e22'
yellow  = '#7e450c'
blue    = '#205970'
magenta = '#6d21cb'
cyan    = '#2e5b54'
white   = '#693d0a'