# extras/alacritty/themes/dawnlight/oasis_dawnlight.toml
## name: Oasis Dawnlight
## author: uhs-robert

[colors.primary]
background = '#ECDFA3'
foreground = '#403423'

[colors.selection]
background = '#D1C085'
text = '#403423'

[colors.cursor]
cursor = '#59531e'
text = '#464646'

[colors.vi_mode_cursor]
cursor = '#7c440c'
text = '#464646'

[colors.normal]
black   = '#464646'
red     = '#8c3737'
green   = '#295c41'
yellow  = '#59531e'
blue    = '#1250a3'
magenta = '#6d20c8'
cyan    = '#2e5a55'
white   = '#49463f'

[colors.bright]
black   = '#464646'
red     = '#a61111'
green   = '#2e5d22'
yellow  = '#7c440c'
blue    = '#20586f'
magenta = '#6d21c9'
cyan    = '#2e5a53'
white   = '#673c0a'