# extras/wezterm/oasis_starlight.toml
## name: Oasis Starlight
## author: uhs-robert

[colors]
foreground = "#E8E8E8"
background= "#000000"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#080808"
selection_bg= "#4D4528"
selection_fg= "#080808"
split= "#4AC8FF"
compose_cursor= "#FFA247"
scrollbar_thumb= "#1A1A1A"
visual_bell= "#080808"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#ED7777'

[colors.tab_bar]
background = '#080808'
inactive_tab_edge = '#050505'

[colors.tab_bar.active_tab]
bg_color = '#4AC8FF'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1A1A1A'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#080808'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F0E68C'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#F8B471'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight'