# extras/wezterm/oasis_mirage.toml
## name: Oasis Mirage
## author: uhs-robert

[colors]
foreground = "#DDEFEF"
background= "#18252A"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#1A2D33"
selection_bg= "#5A3824"
selection_fg= "#1A2D33"
split= "#5ABAAE"
compose_cursor= "#FFA247"
scrollbar_thumb= "#2A3F46"
visual_bell= "#1A2D33"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F39493'

[colors.tab_bar]
background = '#1A2D33'
inactive_tab_edge = '#172328'

[colors.tab_bar.active_tab]
bg_color = '#5ABAAE'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#2A3F46'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#1A2D33'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA247'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#C799FF'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage'