# extras/wezterm/oasis_night.toml
## name: Oasis Night
## author: uhs-robert

[colors]
foreground = "#E0E4F8"
background= "#0D0D1A"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#06060E"
selection_bg= "#3E2F4A"
selection_fg= "#06060E"
split= "#D06666"
compose_cursor= "#FFA247"
scrollbar_thumb= "#262633"
visual_bell= "#06060E"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F58888'

[colors.tab_bar]
background = '#06060E'
inactive_tab_edge = '#0C0C18'

[colors.tab_bar.active_tab]
bg_color = '#D06666'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#262633'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#06060E'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA247'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#4AC8FF'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night'