# extras/wezterm/oasis_dune.toml
## name: Oasis Dune
## author: uhs-robert

[colors]
foreground = "#ECE6DF"
background= "#2E2620"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#3C332C"
selection_bg= "#335668"
selection_fg= "#3C332C"
split= "#BDB76B"
compose_cursor= "#FFA247"
scrollbar_thumb= "#534A3F"
visual_bell= "#3C332C"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F29B9B'

[colors.tab_bar]
background = '#3C332C'
inactive_tab_edge = '#2B231E'

[colors.tab_bar.active_tab]
bg_color = '#BDB76B'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#534A3F'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3C332C'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#A7D3A9'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#53D390'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune'