# extras/wezterm/oasis_rose.toml
## name: Oasis Rose
## author: uhs-robert

[colors]
foreground = "#E9E3E8"
background= "#301828"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#3E2636"
selection_bg= "#5A3824"
selection_fg= "#3E2636"
split= "#FFA0A0"
compose_cursor= "#F49F15"
scrollbar_thumb= "#523A4B"
visual_bell= "#3E2636"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#F49F15'
17 = '#F39493'

[colors.tab_bar]
background = '#3E2636'
inactive_tab_edge = '#2B1523'

[colors.tab_bar.active_tab]
bg_color = '#FFA0A0'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#523A4B'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3E2636'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F4E36B'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#87CEEB'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose'