# extras/wezterm/oasis_canyon.toml
## name: Oasis Canyon
## author: uhs-robert

[colors]
foreground = "#F8E7D3"
background= "#2F1A05"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#402412"
selection_bg= "#335668"
selection_fg= "#402412"
split= "#FFA247"
compose_cursor= "#FFD700"
scrollbar_thumb= "#624020"
visual_bell= "#402412"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFD700'
17 = '#F28D8D'

[colors.tab_bar]
background = '#402412'
inactive_tab_edge = '#2B1804'

[colors.tab_bar.active_tab]
bg_color = '#FFA247'
fg_color = '#2F1A05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#624020'
fg_color = '#2F1A05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#402412'
fg_color = '#2F1A05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#5CCEFF'
fg_color = '#2F1A05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#34CB7D'
fg_color = '#2F1A05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon'