# extras/wezterm/oasis_twilight.toml
## name: Oasis Twilight
## author: uhs-robert

[colors]
foreground = "#E6E0F8"
background= "#221B2F"
cursor_bg= "#F0E68C"
cursor_border= "#F0E68C"
cursor_fg= "#2B243B"
selection_bg= "#5A3824"
selection_fg= "#2B243B"
split= "#C799FF"
compose_cursor= "#FFA247"
scrollbar_thumb= "#352D47"
visual_bell= "#2B243B"

ansi = [
  '#000000',
  '#D06666',
  '#35B56E',
  '#F0E68C',
  '#87CEEB',
  '#B499FF',
  '#1CA1FF',
  '#E8E2D4',
]

brights = [
  '#514742',
  '#FFA0A0',
  '#6BBF59',
  '#FFA247',
  '#6FB8FF',
  '#C0A0FF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F28D8D'

[colors.tab_bar]
background = '#2B243B'
inactive_tab_edge = '#201C2B'

[colors.tab_bar.active_tab]
bg_color = '#C799FF'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#352D47'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#2B243B'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#EADD61'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#34CB7D'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight'