# extras/wezterm/oasis_midnight.toml
## name: Oasis Midnight
## author: uhs-robert

[colors]
foreground = "#E1E9FF"
background= "#101418"
cursor_bg= "#F28D8D"
cursor_border= "#F28D8D"
cursor_fg= "#14181C"
selection_bg= "#5A3824"
selection_fg= "#14181C"
split= "#D06666"
compose_cursor= "#FFA247"
scrollbar_thumb= "#1C242C"
visual_bell= "#14181C"

ansi = [
  '#000000',
  '#D06666',
  '#53D390',
  '#F0E68C',
  '#519BFF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#666666',
  '#FFA0A0',
  '#96EA7F',
  '#FFA247',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F0E68C'

[colors.tab_bar]
background = '#14181C'
inactive_tab_edge = '#0C1014'

[colors.tab_bar.active_tab]
bg_color = '#D06666'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1C242C'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#14181C'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA852'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#81C0B6'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight'