# extras/wezterm/oasis_dawnlight.toml
## name: Oasis Dawnlight
## author: uhs-robert

[colors]
foreground = "#403423"
background= "#ECDFA3"
cursor_bg= "#4d470a"
cursor_border= "#4d470a"
cursor_fg= "#DDD091"
selection_bg= "#D1C085"
selection_fg= "#DDD091"
split= "#9B3030"
compose_cursor= "#6f3700"
scrollbar_thumb= "#D1C085"
visual_bell= "#DDD091"

ansi = [
  '#3A3427',
  '#663021',
  '#1b491d',
  '#6b2e00',
  '#10426d',
  '#46259f',
  '#064658',
  '#453826',
]

brights = [
  '#454030',
  '#692c34',
  '#35450d',
  '#533c00',
  '#1f3f71',
  '#4d19a8',
  '#084559',
  '#443f36',
]

[colors.indexed]
16 = '#6f3700'
17 = '#8c1313'

[colors.tab_bar]
background = '#DDD091'
inactive_tab_edge = '#E3D396'

[colors.tab_bar.active_tab]
bg_color = '#9B3030'
fg_color = '#ECDFA3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#D1C085'
fg_color = '#ECDFA3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#DDD091'
fg_color = '#ECDFA3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#124977'
fg_color = '#ECDFA3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#124977'
fg_color = '#ECDFA3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dawnlight'