# extras/alacritty/themes/midnight_light_3/oasis_midnight_light_3.toml
## name: Oasis Midnight Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e2d4'
foreground = '#524943'

[colors.selection]
background = '#f0c8ad'
text = '#524943'

[colors.cursor]
cursor = '#5e581f'
text = '#4b4b4b'

[colors.vi_mode_cursor]
cursor = '#83480d'
text = '#4b4b4b'

[colors.normal]
black   = '#4b4b4b'
red     = '#933a3a'
green   = '#2b6144'
yellow  = '#5e581f'
blue    = '#1354ac'
magenta = '#7323d2'
cyan    = '#315e59'
white   = '#4e4b43'

[colors.bright]
black   = '#4b4b4b'
red     = '#ae1212'
green   = '#316223'
yellow  = '#83480d'
blue    = '#215d75'
magenta = '#7223d3'
cyan    = '#305f58'
white   = '#6e400b'