# extras/wezterm/oasis_desert_light_3.toml
## name: Oasis Desert Light 3
## author: uhs-robert

[colors]
foreground = "#514c47"
background= "#f7e6d4"
cursor_bg= "#635918"
cursor_border= "#635918"
cursor_fg= "#f5dfc7"
selection_bg= "#f0d0ad"
selection_fg= "#f5dfc7"
split= "#753c3c"
compose_cursor= "#6d431a"
scrollbar_thumb= "#f0d0ad"
visual_bell= "#f5dfc7"

ansi = [
  '#4c4c4c',
  '#953b3b',
  '#2c6346',
  '#605920',
  '#1356b0',
  '#7523d6',
  '#32605b',
  '#4f4c45',
]

brights = [
  '#4c4c4c',
  '#b11212',
  '#326424',
  '#86490d',
  '#225f77',
  '#7423d7',
  '#31605a',
  '#70410b',
]

[colors.indexed]
16 = '#6d431a'
17 = '#af1a13'

[colors.tab_bar]
background = '#f5dfc7'
inactive_tab_edge = '#f2d7ba'

[colors.tab_bar.active_tab]
bg_color = '#702424'
fg_color = '#f7e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#f0d0ad'
fg_color = '#f7e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f5dfc7'
fg_color = '#f7e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#897e15'
fg_color = '#f7e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#196685'
fg_color = '#f7e6d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 3'