# extras/alacritty/oasis_day.toml
## name: Oasis Day
## author: uhs-robert

[colors.primary]
background = '#E5D68B'
foreground = '#392E1D'

[colors.selection]
background = '#D3BA68'
text = '#392E1D'

[colors.cursor]
cursor = '#6b2e00'
text = '#3A3427'

[colors.vi_mode_cursor]
cursor = '#533c00'
text = '#3A3427'

[colors.normal]
black   = '#3A3427'
red     = '#663021'
green   = '#1b491d'
yellow  = '#6b2e00'
blue    = '#10426d'
magenta = '#46259f'
cyan    = '#064658'
white   = '#453826'

[colors.bright]
black   = '#454030'
red     = '#692c34'
green   = '#35450d'
yellow  = '#533c00'
blue    = '#1f3f71'
magenta = '#4d19a8'
cyan    = '#084559'
white   = '#443f36'