# extras/alacritty/oasis_abyss.toml
## name: Oasis Abyss
## author: uhs-robert

[colors.primary]
background = '#000000'
foreground = '#D5D9E2'

[colors.selection]
background = '#5A3824'
text = '#D5D9E2'

[colors.cursor]
cursor = '#F0E68C'
text = '#000000'

[colors.vi_mode_cursor]
cursor = '#6BBF59'
text = '#000000'

[colors.normal]
black   = '#000000'
red     = '#D06666'
green   = '#35B56E'
yellow  = '#F0E68C'
blue    = '#87CEEB'
magenta = '#B499FF'
cyan    = '#1CA1FF'
white   = '#E8E2D4'

[colors.bright]
black   = '#514742'
red     = '#FFA0A0'
green   = '#6BBF59'
yellow  = '#FFA247'
blue    = '#6FB8FF'
magenta = '#C0A0FF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'