# extras/alacritty/oasis_dust.toml
## name: Oasis Dust
## author: uhs-robert

[colors.primary]
background = '#D4B165'
foreground = '#181309'

[colors.selection]
background = '#C39E4F'
text = '#181309'

[colors.cursor]
cursor = '#6b2e00'
text = '#3A3427'

[colors.vi_mode_cursor]
cursor = '#35450d'
text = '#3A3427'

[colors.normal]
black   = '#3A3427'
red     = '#663021'
green   = '#1b491d'
yellow  = '#6b2e00'
blue    = '#10426d'
magenta = '#46259f'
cyan    = '#064658'
white   = '#453826'

[colors.bright]
black   = '#454030'
red     = '#692c34'
green   = '#35450d'
yellow  = '#533c00'
blue    = '#1f3f71'
magenta = '#4d19a8'
cyan    = '#084559'
white   = '#443f36'