# extras/alacritty/themes/light/1/oasis_midnight_light_1.toml
## name: Oasis Midnight Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f6f5'
foreground = '#5c534c'

[colors.selection]
background = '#e8dcd8'
text = '#5c534c'

[colors.cursor]
cursor = '#b9252a'
text = '#f9f6f5'

[colors.vi_mode_cursor]
cursor = '#8e5215'
text = '#f9f6f5'

[colors.normal]
black   = '#545454'
red     = '#c11313'
green   = '#2f6c4c'
yellow  = '#696223'
blue    = '#1561ad'
magenta = '#7f30dd'
cyan    = '#376962'
white   = '#57544c'

[colors.bright]
black   = '#5b534d'
red     = '#c11313'
green   = '#366d27'
yellow  = '#8e5215'
blue    = '#266783'
magenta = '#7e30dd'
cyan    = '#356a61'
white   = '#7c480c'