# extras/alacritty/themes/light/1/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f7f5'
foreground = '#5c534b'

[colors.selection]
background = '#e8e0d8'
text = '#5c534b'

[colors.cursor]
cursor = '#bb2328'
text = '#f9f7f5'

[colors.vi_mode_cursor]
cursor = '#8f5215'
text = '#f9f7f5'

[colors.normal]
black   = '#555555'
red     = '#b72a2a'
green   = '#306c4c'
yellow  = '#696220'
blue    = '#1662ae'
magenta = '#7f30dd'
cyan    = '#376a62'
white   = '#58554c'

[colors.bright]
black   = '#5c534d'
red     = '#c21313'
green   = '#366d27'
yellow  = '#8f5215'
blue    = '#266884'
magenta = '#7f31de'
cyan    = '#356a62'
white   = '#7d490c'