# extras/alacritty/themes/light/1/oasis_rose_light_1.toml
## name: Oasis Rose Light 1
## author: uhs-robert

[colors.primary]
background = '#fbf9fb'
foreground = '#694e63'

[colors.selection]
background = '#e9dde9'
text = '#694e63'

[colors.cursor]
cursor = '#c3151c'
text = '#fbf9fb'

[colors.vi_mode_cursor]
cursor = '#915315'
text = '#fbf9fb'

[colors.normal]
black   = '#565656'
red     = '#c41414'
green   = '#306e4d'
yellow  = '#6a6423'
blue    = '#1663b0'
magenta = '#8133dd'
cyan    = '#376b64'
white   = '#59564d'

[colors.bright]
black   = '#5d554e'
red     = '#c41414'
green   = '#376f28'
yellow  = '#915315'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#7e4a0d'