# extras/alacritty/themes/light/1/oasis_desert_light_1.toml
## name: Oasis Desert Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f7f5'
foreground = '#63523d'

[colors.selection]
background = '#e8e0d8'
text = '#63523d'

[colors.cursor]
cursor = '#6d6119'
text = '#f9f7f5'

[colors.vi_mode_cursor]
cursor = '#8f5215'
text = '#f9f7f5'

[colors.normal]
black   = '#555555'
red     = '#c21313'
green   = '#306c4c'
yellow  = '#696223'
blue    = '#1662af'
magenta = '#8030de'
cyan    = '#366a64'
white   = '#58554c'

[colors.bright]
black   = '#5f5349'
red     = '#c21313'
green   = '#366d27'
yellow  = '#8f5215'
blue    = '#266884'
magenta = '#7f31de'
cyan    = '#356a62'
white   = '#7d490c'