# extras/alacritty/themes/light/1/oasis_twilight_light_1.toml
## name: Oasis Twilight Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f9fb'
foreground = '#5b4f7e'

[colors.selection]
background = '#dddde9'
text = '#5b4f7e'

[colors.cursor]
cursor = '#8724e7'
text = '#f9f9fb'

[colors.vi_mode_cursor]
cursor = '#905315'
text = '#f9f9fb'

[colors.normal]
black   = '#565656'
red     = '#c41414'
green   = '#306d4d'
yellow  = '#6a6323'
blue    = '#1663b1'
magenta = '#8132de'
cyan    = '#376b65'
white   = '#59564d'

[colors.bright]
black   = '#5d544e'
red     = '#c41414'
green   = '#376e28'
yellow  = '#905315'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#7e490d'