# extras/alacritty/themes/light/1/oasis_mirage_light_1.toml
## name: Oasis Mirage Light 1
## author: uhs-robert

[colors.primary]
background = '#f9fbfa'
foreground = '#455b5b'

[colors.selection]
background = '#dde9e3'
text = '#455b5b'

[colors.cursor]
cursor = '#356c63'
text = '#f9fbfa'

[colors.vi_mode_cursor]
cursor = '#925416'
text = '#f9fbfa'

[colors.normal]
black   = '#575757'
red     = '#bb2b2b'
green   = '#306e4e'
yellow  = '#6b6421'
blue    = '#1664b1'
magenta = '#8234de'
cyan    = '#386c64'
white   = '#59564e'

[colors.bright]
black   = '#5e554f'
red     = '#c51414'
green   = '#376f28'
yellow  = '#925416'
blue    = '#266a86'
magenta = '#8134de'
cyan    = '#366c63'
white   = '#7f4a0d'