# extras/alacritty/themes/light/1/oasis_dune_light_1.toml
## name: Oasis Dune Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f8f5'
foreground = '#58554c'

[colors.selection]
background = '#e8e4d8'
text = '#58554c'

[colors.cursor]
cursor = '#696323'
text = '#555555'

[colors.vi_mode_cursor]
cursor = '#93500e'
text = '#555555'

[colors.normal]
black   = '#555555'
red     = '#a54040'
green   = '#306d4d'
yellow  = '#696323'
blue    = '#155ec1'
magenta = '#8031dd'
cyan    = '#376a63'
white   = '#58554d'

[colors.bright]
black   = '#555555'
red     = '#c21414'
green   = '#366e27'
yellow  = '#93500e'
blue    = '#266884'
magenta = '#7f32de'
cyan    = '#366a62'
white   = '#7d490c'