# extras/alacritty/themes/light/1/oasis_sol_light_1.toml
## name: Oasis Sol Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f5f5'
foreground = '#814236'

[colors.selection]
background = '#e8d8d8'
text = '#814236'

[colors.cursor]
cursor = '#b6282c'
text = '#f9f5f5'

[colors.vi_mode_cursor]
cursor = '#8e5115'
text = '#f9f5f5'

[colors.normal]
black   = '#545454'
red     = '#a33f3f'
green   = '#2f6b4c'
yellow  = '#686223'
blue    = '#155dbf'
magenta = '#7f2fdd'
cyan    = '#366961'
white   = '#57544c'

[colors.bright]
black   = '#5b534c'
red     = '#c01313'
green   = '#366c27'
yellow  = '#8e5115'
blue    = '#256782'
magenta = '#7e2fdd'
cyan    = '#356961'
white   = '#7b480c'