# extras/alacritty/themes/light/1/oasis_lagoon_light_1.toml
## name: Oasis Lagoon Light 1
## author: uhs-robert

[colors.primary]
background = '#f9fafb'
foreground = '#40577a'

[colors.selection]
background = '#dde3e9'
text = '#40577a'

[colors.cursor]
cursor = '#1665aa'
text = '#f9fafb'

[colors.vi_mode_cursor]
cursor = '#915315'
text = '#f9fafb'

[colors.normal]
black   = '#565656'
red     = '#ba2b2b'
green   = '#306e4e'
yellow  = '#6a6421'
blue    = '#1663b1'
magenta = '#8133dd'
cyan    = '#386b64'
white   = '#59564e'

[colors.bright]
black   = '#5d554e'
red     = '#c41414'
green   = '#376f28'
yellow  = '#915315'
blue    = '#266a86'
magenta = '#8033de'
cyan    = '#366c63'
white   = '#7e4a0d'