# extras/alacritty/themes/day/oasis_day.toml
## name: Oasis Day
## author: uhs-robert

[colors.primary]
background = '#E5D68B'
foreground = '#392E1D'

[colors.selection]
background = '#D3BA68'
text = '#392E1D'

[colors.cursor]
cursor = '#534e1c'
text = '#404040'

[colors.vi_mode_cursor]
cursor = '#743f0b'
text = '#404040'

[colors.normal]
black   = '#404040'
red     = '#823333'
green   = '#26563c'
yellow  = '#534e1c'
blue    = '#104a98'
magenta = '#661ebb'
cyan    = '#2b534f'
white   = '#43413a'

[colors.bright]
black   = '#404040'
red     = '#9b1010'
green   = '#2b561f'
yellow  = '#743f0b'
blue    = '#1e5268'
magenta = '#651fbb'
cyan    = '#2a544d'
white   = '#5f3709'