# extras/alacritty/themes/dune_light_2/oasis_dune_light_2.toml
## name: Oasis Dune Light 2
## author: uhs-robert

[colors.primary]
background = '#f9f8ec'
foreground = '#58563e'

[colors.selection]
background = '#eeebc9'
text = '#58563e'

[colors.cursor]
cursor = '#6a6223'
text = '#555555'

[colors.vi_mode_cursor]
cursor = '#93500e'
text = '#555555'

[colors.normal]
black   = '#555555'
red     = '#a44040'
green   = '#316c4c'
yellow  = '#6a6223'
blue    = '#155ebf'
magenta = '#8030dd'
cyan    = '#366964'
white   = '#58554c'

[colors.bright]
black   = '#555555'
red     = '#c21414'
green   = '#376d28'
yellow  = '#93500e'
blue    = '#266883'
magenta = '#7f31dd'
cyan    = '#366a62'
white   = '#7c480c'