# extras/alacritty/themes/dune_light_5/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors.primary]
background = '#ece6c6'
foreground = '#4e4b36'

[colors.selection]
background = '#e1d7a4'
text = '#4e4b36'

[colors.cursor]
cursor = '#5e581f'
text = '#4a4a4a'

[colors.vi_mode_cursor]
cursor = '#83470d'
text = '#4a4a4a'

[colors.normal]
black   = '#4a4a4a'
red     = '#923a3a'
green   = '#2b6144'
yellow  = '#5e581f'
blue    = '#1354ac'
magenta = '#7322d1'
cyan    = '#315e58'
white   = '#4d4a43'

[colors.bright]
black   = '#4a4a4a'
red     = '#ae1111'
green   = '#306123'
yellow  = '#83470d'
blue    = '#225d75'
magenta = '#7222d2'
cyan    = '#305f57'
white   = '#6d400b'