# extras/alacritty/themes/dune_light_3/oasis_dune_light_3.toml
## name: Oasis Dune Light 3
## author: uhs-robert

[colors.primary]
background = '#f4f2dd'
foreground = '#54523b'

[colors.selection]
background = '#e9e5ba'
text = '#54523b'

[colors.cursor]
cursor = '#665f22'
text = '#515151'

[colors.vi_mode_cursor]
cursor = '#8d4d0e'
text = '#515151'

[colors.normal]
black   = '#515151'
red     = '#9e3e3e'
green   = '#2f684a'
yellow  = '#665f22'
blue    = '#145ab9'
magenta = '#7b2adc'
cyan    = '#35665f'
white   = '#545149'

[colors.bright]
black   = '#515151'
red     = '#bb1313'
green   = '#356926'
yellow  = '#8d4d0e'
blue    = '#24647e'
magenta = '#7a2adc'
cyan    = '#34665f'
white   = '#77450c'