# extras/alacritty/themes/dune_light_5/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors.primary]
background = '#ece1c6'
foreground = '#4a4940'

[colors.selection]
background = '#e1cfa4'
text = '#4a4940'

[colors.cursor]
cursor = '#5b551e'
text = '#484848'

[colors.vi_mode_cursor]
cursor = '#80460d'
text = '#484848'

[colors.normal]
black   = '#484848'
red     = '#8f3838'
green   = '#2a5e42'
yellow  = '#5b551e'
blue    = '#1352a8'
magenta = '#7121cc'
cyan    = '#305c56'
white   = '#4a4841'

[colors.bright]
black   = '#484848'
red     = '#aa1111'
green   = '#2f5f22'
yellow  = '#80460d'
blue    = '#215b72'
magenta = '#6f22cd'
cyan    = '#2f5c55'
white   = '#6a3e0b'