# extras/alacritty/themes/dune_light_3/oasis_dune_light_3.toml
## name: Oasis Dune Light 3
## author: uhs-robert

[colors.primary]
background = '#f4efdd'
foreground = '#525047'

[colors.selection]
background = '#e9dfba'
text = '#525047'

[colors.cursor]
cursor = '#645d21'
text = '#505050'

[colors.vi_mode_cursor]
cursor = '#8b4c0e'
text = '#505050'

[colors.normal]
black   = '#505050'
red     = '#9b3d3d'
green   = '#2e6749'
yellow  = '#645d21'
blue    = '#1459b7'
magenta = '#7a27db'
cyan    = '#34645e'
white   = '#535048'

[colors.bright]
black   = '#505050'
red     = '#b81313'
green   = '#346826'
yellow  = '#8b4c0e'
blue    = '#23637c'
magenta = '#7928dc'
cyan    = '#33645d'
white   = '#76440b'