# extras/alacritty/themes/dune_light_1/oasis_dune_light_1.toml
## name: Oasis Dune Light 1
## author: uhs-robert

[colors.primary]
background = '#fbfaf9'
foreground = '#5a5740'

[colors.selection]
background = '#e9e3dd'
text = '#5a5740'

[colors.cursor]
cursor = '#6b6424'
text = '#565656'

[colors.vi_mode_cursor]
cursor = '#95510e'
text = '#565656'

[colors.normal]
black   = '#565656'
red     = '#a74141'
green   = '#306e4e'
yellow  = '#6b6424'
blue    = '#155fc4'
magenta = '#8133dd'
cyan    = '#386b64'
white   = '#59564e'

[colors.bright]
black   = '#565656'
red     = '#c51414'
green   = '#376f28'
yellow  = '#95510e'
blue    = '#266a86'
magenta = '#8134de'
cyan    = '#366c63'
white   = '#7f4a0d'