# extras/alacritty/themes/dune_light_4/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors.primary]
background = '#f5dfc7'
foreground = '#4e483f'

[colors.selection]
background = '#eec9a0'
text = '#4e483f'

[colors.cursor]
cursor = '#5c561f'
text = '#494949'

[colors.vi_mode_cursor]
cursor = '#80460d'
text = '#494949'

[colors.normal]
black   = '#494949'
red     = '#8f3838'
green   = '#2a5f43'
yellow  = '#5c561f'
blue    = '#1252a8'
magenta = '#7121cd'
cyan    = '#305c56'
white   = '#4b4941'

[colors.bright]
black   = '#494949'
red     = '#aa1010'
green   = '#306023'
yellow  = '#80460d'
blue    = '#205b73'
magenta = '#7021cf'
cyan    = '#2f5d56'
white   = '#6b3e0b'