# extras/alacritty/themes/dune_light_4/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors.primary]
background = '#f0ecd1'
foreground = '#514e39'

[colors.selection]
background = '#e5deae'
text = '#514e39'

[colors.cursor]
cursor = '#625b21'
text = '#4e4e4e'

[colors.vi_mode_cursor]
cursor = '#884a0d'
text = '#4e4e4e'

[colors.normal]
black   = '#4e4e4e'
red     = '#983c3c'
green   = '#2d6447'
yellow  = '#625b21'
blue    = '#1357b2'
magenta = '#7723da'
cyan    = '#32625c'
white   = '#504e46'

[colors.bright]
black   = '#4e4e4e'
red     = '#b41111'
green   = '#336525'
yellow  = '#884a0d'
blue    = '#226179'
magenta = '#7623db'
cyan    = '#32625b'
white   = '#72430b'