# extras/wezterm/oasis_rose_dark.toml
## name: Oasis Rose Dark
## author: uhs-robert

[colors]
foreground = "#EDD5E7"
background= "#301828"
cursor_bg= "#FFA0A0"
cursor_border= "#FFA0A0"
cursor_fg= "#3E2636"
selection_bg= "#5A3824"
selection_fg= "#3E2636"
split= "#FFA0A0"
compose_cursor= "#F49F15"
scrollbar_thumb= "#523A4B"
visual_bell= "#3E2636"

ansi = [
  '#000000',
  '#D06666',
  '#53D390',
  '#F0E68C',
  '#519BFF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#666666',
  '#FFA0A0',
  '#96EA7F',
  '#FFA247',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#F49F15'
17 = '#F0E68C'

[colors.tab_bar]
background = '#3E2636'
inactive_tab_edge = '#2B1523'

[colors.tab_bar.active_tab]
bg_color = '#FFA0A0'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#523A4B'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3E2636'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F4E36B'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#87CEEB'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Dark'