# extras/wezterm/oasis_canyon_light_3.toml
## name: Oasis Canyon Light 3
## author: uhs-robert

[colors]
foreground = "#5d4a33"
background= "#f7e7d4"
cursor_bg = "#89480f"
cursor_border = "#89480f"
cursor_fg= "#f7e7d4"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6d431a"
compose_cursor= "#564d1e"
scrollbar_thumb= "#f0d1ad"
visual_bell= "#f5e0c7"

ansi = [
  '#4d4d4d',
  '#963b3b',
  '#2c6346',
  '#615a20',
  '#1356b0',
  '#7623d7',
  '#32615b',
  '#504d45',
]

brights = [
  '#534c46',
  '#b21212',
  '#326424',
  '#834b14',
  '#225f77',
  '#7523d8',
  '#31615a',
  '#71420b',
]

[colors.indexed]
16 = '#564d1e'
17 = '#a9252a'

[colors.tab_bar]
background = '#f5e0c7'
inactive_tab_edge = '#f2d9ba'

[colors.tab_bar.active_tab]
bg_color = '#914a03'
fg_color = '#f7e7d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#f0d1ad'
fg_color = '#914a03'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f0d1ad'
fg_color = '#196685'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#196685'
fg_color = '#f7e7d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#227c4e'
fg_color = '#f7e7d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 3'