# extras/wezterm/oasis_abyss_light_3.toml
## name: Oasis Abyss Light 3
## author: uhs-robert

[colors]
foreground = "#524b43"
background= "#f7e5d4"
cursor_bg = "#aa2126"
cursor_border = "#aa2126"
cursor_fg= "#f7e5d4"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#842f2f"
compose_cursor= "#6e421b"
scrollbar_thumb= "#f0cead"
visual_bell= "#f5ddc7"

ansi = [
  '#4c4c4c',
  '#a72626',
  '#2c6245',
  '#60591d',
  '#13599e',
  '#7523d5',
  '#32605a',
  '#4f4c44',
]

brights = [
  '#524b45',
  '#b01212',
  '#326324',
  '#824a14',
  '#225f77',
  '#7423d6',
  '#316059',
  '#70410b',
]

[colors.indexed]
16 = '#6e421b'
17 = '#5e592b'

[colors.tab_bar]
background = '#f5ddc7'
inactive_tab_edge = '#f2d5ba'

[colors.tab_bar.active_tab]
bg_color = '#801414'
fg_color = '#f7e5d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#f0cead'
fg_color = '#801414'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f0cead'
fg_color = '#944f0a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#944f0a'
fg_color = '#f7e5d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#366860'
fg_color = '#f7e5d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 3'