# extras/wezterm/oasis_mirage_light_3.toml
## name: Oasis Mirage Light 3
## author: uhs-robert

[colors]
foreground = "#405454"
background= "#dbf5f5"
cursor_bg = "#32655d"
cursor_border = "#32655d"
cursor_fg= "#dbf5f5"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#355752"
compose_cursor= "#72461c"
scrollbar_thumb= "#b7ebeb"
visual_bell= "#cff2f2"

ansi = [
  '#505050',
  '#b91313',
  '#2e6749',
  '#655e21',
  '#145ea7',
  '#7b28dc',
  '#34655f',
  '#535048',
]

brights = [
  '#574f49',
  '#b91313',
  '#346926',
  '#894e15',
  '#24647d',
  '#7929dc',
  '#33655e',
  '#76450c',
]

[colors.indexed]
16 = '#72461c'
17 = '#b0262a'

[colors.tab_bar]
background = '#cff2f2'
inactive_tab_edge = '#c3eeee'

[colors.tab_bar.active_tab]
bg_color = '#32625a'
fg_color = '#dbf5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#b7ebeb'
fg_color = '#32625a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#b7ebeb'
fg_color = '#944f0a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#944f0a'
fg_color = '#dbf5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#49039b'
fg_color = '#dbf5f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 3'