# extras/wezterm/oasis_midnight_light_3.toml
## name: Oasis Midnight Light 3
## author: uhs-robert

[colors]
foreground = "#524943"
background= "#f7e2d4"
cursor_bg = "#a82025"
cursor_border = "#a82025"
cursor_fg= "#f7e2d4"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#8d2222"
compose_cursor= "#6b411a"
scrollbar_thumb= "#f0c8ad"
visual_bell= "#f5d9c7"

ansi = [
  '#4b4b4b',
  '#ae1212',
  '#2b6144',
  '#5e581f',
  '#13589c',
  '#7322d2',
  '#305e59',
  '#4e4b43',
]

brights = [
  '#534941',
  '#ae1212',
  '#316223',
  '#804913',
  '#215d75',
  '#7223d3',
  '#305f58',
  '#6e400b',
]

[colors.indexed]
16 = '#6b411a'
17 = '#625718'

[colors.tab_bar]
background = '#f5d9c7'
inactive_tab_edge = '#f2d1ba'

[colors.tab_bar.active_tab]
bg_color = '#910303'
fg_color = '#f7e2d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#f0c8ad'
fg_color = '#910303'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f0c8ad'
fg_color = '#944f0a'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#944f0a'
fg_color = '#f7e2d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2f6f65'
fg_color = '#f7e2d4'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 3'