# extras/wezterm/oasis_dune_light_3.toml
## name: Oasis Dune Light 3
## author: uhs-robert

[colors]
foreground = "#525047"
background= "#f4efdd"
cursor_bg = "#685c19"
cursor_border = "#685c19"
cursor_fg= "#f4efdd"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#535139"
compose_cursor= "#73461c"
scrollbar_thumb= "#e9dfba"
visual_bell= "#f0ead1"

ansi = [
  '#505050',
  '#b81313',
  '#2e6749',
  '#645d21',
  '#145da5',
  '#7a26dc',
  '#33645f',
  '#535048',
]

brights = [
  '#594e45',
  '#b81313',
  '#346826',
  '#884e14',
  '#23637c',
  '#7928dc',
  '#33645d',
  '#76440b',
]

[colors.indexed]
16 = '#73461c'
17 = '#ad2a2e'

[colors.tab_bar]
background = '#f0ead1'
inactive_tab_edge = '#ede4c6'

[colors.tab_bar.active_tab]
bg_color = '#817613'
fg_color = '#f4efdd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9dfba'
fg_color = '#817613'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9dfba'
fg_color = '#2f6f65'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2f6f65'
fg_color = '#f4efdd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#48039b'
fg_color = '#f4efdd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 3'