# extras/wezterm/oasis_cactus_light_3.toml
## name: Oasis Cactus Light 3
## author: uhs-robert

[colors]
foreground = "#405348"
background= "#e0f0e7"
cursor_bg= "#3a643d"
cursor_border= "#3a643d"
cursor_fg= "#d6ebdf"
selection_bg= "#c1e1cf"
selection_fg= "#d6ebdf"
split= "#3e543f"
compose_cursor= "#6f451b"
scrollbar_thumb= "#c1e1cf"
visual_bell= "#d6ebdf"

ansi = [
  '#4e4e4e',
  '#993c3c',
  '#2d6547',
  '#625c21',
  '#1358b4',
  '#7824da',
  '#33635d',
  '#514e47',
]

brights = [
  '#4e4e4e',
  '#b51212',
  '#336625',
  '#894b0d',
  '#23617a',
  '#7725db',
  '#32635c',
  '#73430b',
]

[colors.indexed]
16 = '#6f451b'
17 = '#ac2529'

[colors.tab_bar]
background = '#d6ebdf'
inactive_tab_edge = '#cbe6d7'

[colors.tab_bar.active_tab]
bg_color = '#346036'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c1e1cf'
fg_color = '#405348'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d6ebdf'
fg_color = '#405348'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9b0303'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9b0303'
fg_color = '#e0f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 3'