# extras/wezterm/oasis_starlight_light_3.toml
## name: Oasis Starlight Light 3
## author: uhs-robert

[colors]
foreground = "#564f3e"
background= "#f4eddd"
cursor_bg = "#135d9e"
cursor_border = "#135d9e"
cursor_fg= "#f4eddd"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#205377"
compose_cursor= "#71451b"
scrollbar_thumb= "#e9dbba"
visual_bell= "#f0e7d1"

ansi = [
  '#4f4f4f',
  '#ad2727',
  '#2e6648',
  '#635c1e',
  '#145ca4',
  '#7925db',
  '#34635d',
  '#524f47',
]

brights = [
  '#554e48',
  '#b71212',
  '#336725',
  '#874d14',
  '#23627b',
  '#7826dc',
  '#33645d',
  '#74440b',
]

[colors.indexed]
16 = '#71451b'
17 = '#ab2a2e'

[colors.tab_bar]
background = '#f0e7d1'
inactive_tab_edge = '#ede1c6'

[colors.tab_bar.active_tab]
bg_color = '#05558f'
fg_color = '#f4eddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9dbba'
fg_color = '#05558f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e9dbba'
fg_color = '#897e15'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#897e15'
fg_color = '#f4eddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#944f0a'
fg_color = '#f4eddd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 3'