# extras/alacritty/themes/rose_light_1/oasis_rose_light_1.toml
## name: Oasis Rose Light 1
## author: uhs-robert

[colors.primary]
background = '#fbf9fb'
foreground = '#694e63'

[colors.selection]
background = '#e9dde9'
text = '#694e63'

[colors.cursor]
cursor = '#6a6423'
text = '#565656'

[colors.vi_mode_cursor]
cursor = '#95510e'
text = '#565656'

[colors.normal]
black   = '#565656'
red     = '#a64141'
green   = '#306e4d'
yellow  = '#6a6423'
blue    = '#155fc3'
magenta = '#8133dd'
cyan    = '#376b64'
white   = '#59564d'

[colors.bright]
black   = '#565656'
red     = '#c41414'
green   = '#376f28'
yellow  = '#95510e'
blue    = '#266985'
magenta = '#8033de'
cyan    = '#366b63'
white   = '#7e4a0d'