# starship/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â•­](bright_black)[î‚¶](light_primary)$os$username$sudo[î‚°](fg:light_primary)\
$hostname$localip\
[îƒ—](fg:bright_blue)$directory[î‚°](fg:bright_blue)\
$git_branch$git_status\
$cmd_duration\
$status\
$fill\
$c$rust$golang$nodejs$lua$php$java$kotlin$haskell$python\
$docker_context$conda\
[î‚¶](fg:bright_black bg:none)$time[î‚´](fg:bright_black bg:none)\
[ ](fg: none bg: none)$line_break\
[â•°â”€](fg:bright_black)$character\
"""

palette = 'oasis'
[palettes.oasis]
primary = "#1CA0FD"
light_primary = "#58B8FD"
secondary = "#F8B471"
accent = "#FFA0A0"
fg_core = "#D9E6FA"
bg_core = "#101825"
surface = "#22385C"
black = "#000000"
bright_black = "#504641"
red = "#D06666"
bright_red = "#FFA0A0"
green = "#53D390"
bright_green = "#96EA7F"
yellow = "#F0E68C"
bright_yellow = "#F8B471"
blue = "#519BFF"
bright_blue = "#87CEEB"
magenta = "#C28EFF"
bright_magenta = "#D2ADFF"
cyan = "#5ABAAE"
bright_cyan = "#8FD1C7"
white = "#DDDBD5"
bright_white = "#FFF9F2"

[os]
disabled = false
style = "bg:light_primary fg:bg_core"

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
AOSC = "ïŒ "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Elementary = "ïŒ‰ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Ios = "ó°€· "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
Zorin = "ïŒ¯ "

[username]
show_always = true
style_user = "bg:light_primary fg:bg_core"
style_root = "bg:bright_red fg:bg_core"
format = '[$user ]($style)'

[sudo]
disabled = true
style = "bg:bright_red fg:bg_core"

[hostname]
disabled = false
ssh_only = true
style = "fg:fg_core bold bg:red"
ssh_symbol = 'ğŸŒ'
#trim_at = '.companyname.com'
format = '[îƒ—](fg:red bg:none)[ $ssh_symbolğŸŒ$hostname]($style)'

[localip]
disabled = false
ssh_only = true
style = "fg:fg_core bold bg:red"
format = '[ $localipv4 ](fg:fg_core bg:red)[î‚°](fg:red bg:none)'

[directory]
style = "fg:bg_core bg:bright_blue"
format = "[ $path ]($style)"
home_symbol = 'î˜— ~'
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo = true
repo_root_format = '[ ï‚› ](fg:bg_core bg:bright_blue)[$read_only]($read_only_style)[$before_root_path]($style)[$repo_root]($style)[$path ]($style)'
repo_root_style = 'fg:primt bold bg:prim'

[directory.substitutions]
".config" = ".ï€“ "
"Developer" = "ó°²‹ "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Videos" = "ó°¨œ "
"Games" = "ğŸ® "
"steam" = "ï†¶ "
"Emulators" = "ğŸ•¹ï¸ "

[git_branch]
symbol = "ï˜"
style = "bg:bright_yellow"
format = '[îƒ—](fg:bright_yellow bg:none)[[ $symbol $branch(:$remote_branch) ](fg:bg_core bg:bright_yellow)]($style)'

[git_status]
style = "bg:bright_yellow"
format = '[[($all_status $ahead_behind)](fg:bg_core bg:bright_yellow)]($style)[î‚°](fg:bright_yellow bg:none)'

[nodejs]
symbol = 'ó°™ Node'
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[lua]
symbol = "î˜  "
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[c]
symbol = "î˜ C"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[rust]
symbol = "î¨ Rust"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[golang]
symbol = "î˜§ Go"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[php]
symbol = "î˜ˆ Php"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[java]
symbol = 'îœ¸ Java'
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[kotlin]
symbol = "î˜´ Kotlin"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[haskell]
symbol = "î˜Ÿ Haskell"
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[python]
symbol = 'îœ¼ Python'
style = "bg:magenta"
format = '[î‚¶](fg:magenta)[[ $symbol($version) ](fg:bg_core bg:magenta)]($style)[î‚´](fg:magenta)[â”€](fg:bright_black)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:white"
format = '[î‚¶](fg:red)[[ $symbol( $context) ](fg:fg_core bg:red)]($style)[î‚´](fg:red)[â”€](fg:white)'

[conda]
style = "bg:white"
format = '[î‚¶](fg:red)[[ $symbol( $environment) ](fg:fg_core bg:red)]($style)[î‚´](fg:red)[â”€](fg:white)'

[time]
disabled = false
time_format = " %I:%M%P"
style = "bg:bright_black"
format = '[[ ïº $time ](fg:fg_core bg:bright_black)]($style)'

[fill]
symbol = " "

[cmd_duration]
disabled = false
style = "fg:yellow bg:none"
format = '[îƒ—]($style)[ ó±‹ $duration ]($style inverted)[î‚´]($style)'
min_time = 500

[status]
style = "fg:red bg:none"
disabled = false
format = '[â”€](fg:bright_black bg:none)[î‚¶](fg:red bg:none)[$symbol ](fg:bright_white bg:red)[î‚´]($style)'
symbol = ' ïª  Error'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[â¯](bold light_primary)'
error_symbol = '[â¯](bold red)'
vimcmd_symbol = '[î˜«](bold yellow)'
vimcmd_replace_one_symbol = '[R](bold bright_cyan)'
vimcmd_replace_symbol = '[R](bold bright_cyan)'
vimcmd_visual_symbol = '[V](bold bright_yellow)'
