# extras/wezterm/oasis_canyon_light_2.toml
## name: Oasis Canyon Light 2
## author: uhs-robert

[colors]
foreground = "#624e35"
background= "#f8f0e7"
cursor_bg = "#8f4c10"
cursor_border = "#8f4c10"
cursor_fg= "#f8f0e7"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#73471b"
compose_cursor= "#5b5120"
scrollbar_thumb= "#eedac3"
visual_bell= "#f5e9db"

ansi = [
  '#515151',
  '#9e3e3e',
  '#2f6849',
  '#655f22',
  '#145bb9',
  '#7c29dc',
  '#356660',
  '#545149',
]

brights = [
  '#515151',
  '#bb1313',
  '#356926',
  '#8d4d0e',
  '#24647e',
  '#7a2bdc',
  '#34665f',
  '#77450c',
]

[colors.indexed]
16 = '#5b5120'
17 = '#b2272c'

[colors.tab_bar]
background = '#f5e9db'
inactive_tab_edge = '#f1e1cf'

[colors.tab_bar.active_tab]
bg_color = '#994e05'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eedac3'
fg_color = '#994e05'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eedac3'
fg_color = '#1c6c8d'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1c6c8d'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#258353'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Canyon Light 2'