# extras/wezterm/oasis_mirage_light_2.toml
## name: Oasis Mirage Light 2
## author: uhs-robert

[colors]
foreground = "#425858"
background= "#ebf9f9"
cursor_bg = "#356962"
cursor_border = "#356962"
cursor_fg= "#ebf9f9"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#375b56"
compose_cursor= "#78491c"
scrollbar_thumb= "#c8eeee"
visual_bell= "#dff5f5"

ansi = [
  '#545454',
  '#c01313',
  '#306b4c',
  '#686123',
  '#1561ae',
  '#7f2fdd',
  '#366963',
  '#57544b',
]

brights = [
  '#5e5249',
  '#c01313',
  '#366d27',
  '#8e5115',
  '#256782',
  '#7e30dd',
  '#356961',
  '#7b480c',
]

[colors.indexed]
16 = '#78491c'
17 = '#b7282c'

[colors.tab_bar]
background = '#dff5f5'
inactive_tab_edge = '#d3f2f2'

[colors.tab_bar.active_tab]
bg_color = '#316e67'
fg_color = '#ebf9f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c8eeee'
fg_color = '#316e67'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c8eeee'
fg_color = '#9c540c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9c540c'
fg_color = '#ebf9f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#4c05a3'
fg_color = '#ebf9f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 2'