# extras/wezterm/oasis_desert_light_2.toml
## name: Oasis Desert Light 2
## author: uhs-robert

[colors]
foreground = "#5f4e3b"
background= "#f8f0e7"
cursor_bg = "#695e19"
cursor_border = "#695e19"
cursor_fg= "#f8f0e7"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#9a2424"
compose_cursor= "#75461b"
scrollbar_thumb= "#eedac3"
visual_bell= "#f5e9db"

ansi = [
  '#515151',
  '#bb1313',
  '#2f6849',
  '#655f22',
  '#155ea9',
  '#7c2adc',
  '#346660',
  '#545149',
]

brights = [
  '#5b4f47',
  '#bb1313',
  '#356926',
  '#8a4f14',
  '#24647e',
  '#7a2bdc',
  '#34665f',
  '#77450c',
]

[colors.indexed]
16 = '#75461b'
17 = '#b42329'

[colors.tab_bar]
background = '#f5e9db'
inactive_tab_edge = '#f1e1cf'

[colors.tab_bar.active_tab]
bg_color = '#887d16'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eedac3'
fg_color = '#887d16'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eedac3'
fg_color = '#a30505'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a30505'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#348d1b'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 2'