# extras/wezterm/oasis_abyss_light_2.toml
## name: Oasis Abyss Light 2
## author: uhs-robert

[colors]
foreground = "#585048"
background= "#f8f0e7"
cursor_bg = "#b42328"
cursor_border = "#b42328"
cursor_fg= "#f8f0e7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#8d3333"
compose_cursor= "#75461b"
scrollbar_thumb= "#eedac3"
visual_bell= "#f5e9db"

ansi = [
  '#515151',
  '#b12828',
  '#2f6849',
  '#665f1f',
  '#155ea8',
  '#7c29dc',
  '#356660',
  '#545149',
]

brights = [
  '#58504a',
  '#bb1313',
  '#356926',
  '#8a4f14',
  '#24647e',
  '#7a2bdc',
  '#34665f',
  '#77450c',
]

[colors.indexed]
16 = '#75461b'
17 = '#645e2d'

[colors.tab_bar]
background = '#f5e9db'
inactive_tab_edge = '#f1e1cf'

[colors.tab_bar.active_tab]
bg_color = '#881616'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eedac3'
fg_color = '#881616'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eedac3'
fg_color = '#9c540c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9c540c'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3a6f66'
fg_color = '#f8f0e7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 2'