# extras/wezterm/oasis_sol_light_2.toml
## name: Oasis Sol Light 2
## author: uhs-robert

[colors]
foreground = "#793e33"
background= "#f8eae7"
cursor_bg= "#ad262a"
cursor_border= "#ad262a"
cursor_fg= "#f5e0db"
selection_bg= "#eecbc3"
selection_fg= "#f5e0db"
split= "#863434"
compose_cursor= "#664a1c"
scrollbar_thumb= "#eecbc3"
visual_bell= "#f5e0db"

ansi = [
  '#4f4f4f',
  '#9a3c3c',
  '#2d6548',
  '#635c21',
  '#1358b4',
  '#7824dc',
  '#33635e',
  '#524f47',
]

brights = [
  '#4f4f4f',
  '#b61212',
  '#336625',
  '#8a4b0d',
  '#23627b',
  '#7826db',
  '#33635c',
  '#74430b',
]

[colors.indexed]
16 = '#664a1c'
17 = '#665c19'

[colors.tab_bar]
background = '#f5e0db'
inactive_tab_edge = '#f1d5cf'

[colors.tab_bar.active_tab]
bg_color = '#851a1a'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eecbc3'
fg_color = '#793e33'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f5e0db'
fg_color = '#793e33'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a35305'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#0761a1'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 2'