# extras/wezterm/oasis_sol_light_2.toml
## name: Oasis Sol Light 2
## author: uhs-robert

[colors]
foreground = "#793e33"
background= "#f8eae7"
cursor_bg = "#ad262a"
cursor_border = "#ad262a"
cursor_fg= "#f8eae7"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#962323"
compose_cursor= "#664a1c"
scrollbar_thumb= "#eecbc3"
visual_bell= "#f5e0db"

ansi = [
  '#4f4f4f',
  '#b61212',
  '#2d6548',
  '#635c21',
  '#145ca4',
  '#7925db',
  '#33635d',
  '#524f47',
]

brights = [
  '#554d48',
  '#b61212',
  '#336625',
  '#864d14',
  '#23627b',
  '#7826db',
  '#33635c',
  '#74430b',
]

[colors.indexed]
16 = '#664a1c'
17 = '#665c19'

[colors.tab_bar]
background = '#f5e0db'
inactive_tab_edge = '#f1d5cf'

[colors.tab_bar.active_tab]
bg_color = '#990505'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eecbc3'
fg_color = '#990505'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eecbc3'
fg_color = '#9c540c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9c540c'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#075ea2'
fg_color = '#f8eae7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 2'