# extras/wezterm/oasis_cactus_light_2.toml
## name: Oasis Cactus Light 2
## author: uhs-robert

[colors]
foreground = "#44584c"
background= "#eef7f2"
cursor_bg = "#3e6940"
cursor_border = "#3e6940"
cursor_fg= "#eef7f2"
selection_bg= "#a4dac0"
selection_fg= "#15472f"
split= "#425943"
compose_cursor= "#76491c"
scrollbar_thumb= "#cfe8da"
visual_bell= "#e4f2ea"

ansi = [
  '#535353',
  '#bf1313',
  '#306b4b',
  '#686123',
  '#1560ad',
  '#7e2ddc',
  '#356862',
  '#56534b',
]

brights = [
  '#5e5149',
  '#bf1313',
  '#366b27',
  '#8d5115',
  '#256681',
  '#7d2fdd',
  '#356861',
  '#7a470c',
]

[colors.indexed]
16 = '#76491c'
17 = '#b5282c'

[colors.tab_bar]
background = '#e4f2ea'
inactive_tab_edge = '#d9ede2'

[colors.tab_bar.active_tab]
bg_color = '#38663b'
fg_color = '#eef7f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#cfe8da'
fg_color = '#38663b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#cfe8da'
fg_color = '#a30505'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#a30505'
fg_color = '#eef7f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#4c05a3'
fg_color = '#eef7f2'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Light 2'