# extras/wezterm/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors]
foreground = "#54432d"
background= "#e9deb9"
cursor_bg = "#7e430e"
cursor_border = "#7e430e"
cursor_fg= "#e9deb9"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#6c3636"
compose_cursor= "#643e17"
scrollbar_thumb= "#decd96"
visual_bell= "#e5d8ae"

ansi = [
  '#464646',
  '#8b3636',
  '#295c41',
  '#59531e',
  '#1250a3',
  '#6d20c7',
  '#2e5955',
  '#48463f',
]

brights = [
  '#4c4540',
  '#a51111',
  '#2e5c22',
  '#794512',
  '#20586f',
  '#6c21c8',
  '#2e5a53',
  '#673c0a',
]

[colors.indexed]
16 = '#643e17'
17 = '#9d2227'

[colors.tab_bar]
background = '#e5d8ae'
inactive_tab_edge = '#e2d3a2'

[colors.tab_bar.active_tab]
bg_color = '#881616'
fg_color = '#e9deb9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#decd96'
fg_color = '#881616'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#decd96'
fg_color = '#9c540c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9c540c'
fg_color = '#e9deb9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#0761a1'
fg_color = '#e9deb9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 2'