# extras/wezterm/oasis_lagoon_light_2.toml
## name: Oasis Lagoon Light 2
## author: uhs-robert

[colors]
foreground = "#3d5273"
background= "#ebf1f9"
cursor_bg = "#135fa2"
cursor_border = "#135fa2"
cursor_fg= "#ebf1f9"
selection_bg= "#9fcae0"
selection_fg= "#0f384c"
split= "#21557a"
compose_cursor= "#75461b"
scrollbar_thumb= "#c8d8ee"
visual_bell= "#dfe9f5"

ansi = [
  '#515151',
  '#b02828',
  '#2f6849',
  '#655e1f',
  '#155ea7',
  '#7b28dc',
  '#346560',
  '#535148',
]

brights = [
  '#574f49',
  '#ba1313',
  '#346926',
  '#894f14',
  '#24647e',
  '#7a2adc',
  '#34655e',
  '#77450c',
]

[colors.indexed]
16 = '#75461b'
17 = '#b32328'

[colors.tab_bar]
background = '#dfe9f5'
inactive_tab_edge = '#d3e1f2'

[colors.tab_bar.active_tab]
bg_color = '#075b98'
fg_color = '#ebf1f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#c8d8ee'
fg_color = '#075b98'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#c8d8ee'
fg_color = '#9c540c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#9c540c'
fg_color = '#ebf1f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#a30505'
fg_color = '#ebf1f9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Lagoon Light 2'