# extras/wezterm/oasis_starlight_light_2.toml
## name: Oasis Starlight Light 2
## author: uhs-robert

[colors]
foreground = "#5b5341"
background= "#f9f5ec"
cursor_bg = "#1462a7"
cursor_border = "#1462a7"
cursor_fg= "#f9f5ec"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#22587e"
compose_cursor= "#77491c"
scrollbar_thumb= "#eee3c9"
visual_bell= "#f5efe0"

ansi = [
  '#545454',
  '#bf1313',
  '#306b4b',
  '#686123',
  '#1561ac',
  '#7e2edd',
  '#366863',
  '#56544b',
]

brights = [
  '#5a524c',
  '#bf1313',
  '#366c27',
  '#8d5115',
  '#256781',
  '#7d2fdd',
  '#356961',
  '#7a470c',
]

[colors.indexed]
16 = '#77491c'
17 = '#be151c'

[colors.tab_bar]
background = '#f5efe0'
inactive_tab_edge = '#f2e9d5'

[colors.tab_bar.active_tab]
bg_color = '#075b98'
fg_color = '#f9f5ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eee3c9'
fg_color = '#075b98'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eee3c9'
fg_color = '#918517'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#918517'
fg_color = '#f9f5ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#9c540c'
fg_color = '#f9f5ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 2'