# extras/wezterm/oasis_midnight_dark.toml
## name: Oasis Midnight Dark
## author: uhs-robert

[colors]
foreground = "#F7F4F2"
background= "#101418"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#101418"
selection_bg= "#5A3824"
selection_fg= "#F7F4F2"
split= "#FF7979"
compose_cursor= "#FFA247"
scrollbar_thumb= "#1C242C"
visual_bell= "#14181C"

ansi = [
  '#101010',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#504641',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F0E68C'

[colors.tab_bar]
background = '#14181C'
inactive_tab_edge = '#0C1014'

[colors.tab_bar.active_tab]
bg_color = '#FF7979'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1C242C'
fg_color = '#FF7979'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#1C242C'
fg_color = '#F8B471'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F8B471'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8FD1C7'
fg_color = '#101418'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Dark'