# extras/wezterm/oasis_rose_dark.toml
## name: Oasis Rose Dark
## author: uhs-robert

[colors]
foreground = "#EDD5E7"
background= "#301828"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#301828"
selection_bg= "#345A2B"
selection_fg= "#EDD5E7"
split= "#FF8080"
compose_cursor= "#FF9633"
scrollbar_thumb= "#523A4B"
visual_bell= "#3E2636"

ansi = [
  '#301828',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#816175',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF9633'
17 = '#F0E68C'

[colors.tab_bar]
background = '#3E2636'
inactive_tab_edge = '#2B1523'

[colors.tab_bar.active_tab]
bg_color = '#FF9090'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#523A4B'
fg_color = '#FF9090'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#523A4B'
fg_color = '#A7D3A9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#A7D3A9'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8FD1C7'
fg_color = '#301828'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Rose Dark'