# extras/wezterm/oasis_desert_dark.toml
## name: Oasis Desert Dark
## author: uhs-robert

[colors]
foreground = "#F7EDE1"
background= "#333333"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#333333"
selection_bg= "#5A3824"
selection_fg= "#F7EDE1"
split= "#D06666"
compose_cursor= "#FFA852"
scrollbar_thumb= "#555555"
visual_bell= "#444444"

ansi = [
  '#000000',
  '#D06666',
  '#53D390',
  '#F0E68C',
  '#519BFF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#666666',
  '#FFA0A0',
  '#96EA7F',
  '#FFA247',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA852'
17 = '#FFACA5'

[colors.tab_bar]
background = '#444444'
inactive_tab_edge = '#303030'

[colors.tab_bar.active_tab]
bg_color = '#D06666'
fg_color = '#333333'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#555555'
fg_color = '#D06666'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#555555'
fg_color = '#F0E68C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F0E68C'
fg_color = '#333333'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#87CEEB'
fg_color = '#333333'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Dark'