# extras/wezterm/oasis_abyss_dark.toml
## name: Oasis Abyss Dark
## author: uhs-robert

[colors]
foreground = "#F0EBE6"
background= "#000000"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#000000"
selection_bg= "#5A3824"
selection_fg= "#F0EBE6"
split= "#FF7979"
compose_cursor= "#FF8A1F"
scrollbar_thumb= "#1A1A1A"
visual_bell= "#080808"

ansi = [
  '#101010',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#504641',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF8A1F'
17 = '#CDC673'

[colors.tab_bar]
background = '#080808'
inactive_tab_edge = '#000000'

[colors.tab_bar.active_tab]
bg_color = '#FF7979'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1A1A1A'
fg_color = '#FF7979'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#1A1A1A'
fg_color = '#F8B471'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F8B471'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8FD1C7'
fg_color = '#000000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Dark'