# extras/wezterm/oasis_sol_dark.toml
## name: Oasis Sol Dark
## author: uhs-robert

[colors]
foreground = "#FFE0DA"
background= "#2F1815"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#2F1815"
selection_bg= "#5A3824"
selection_fg= "#FFE0DA"
split= "#E87272"
compose_cursor= "#F49F15"
scrollbar_thumb= "#4F312B"
visual_bell= "#3A2521"

ansi = [
  '#000000',
  '#D06666',
  '#53D390',
  '#F0E68C',
  '#519BFF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#666666',
  '#FFA0A0',
  '#96EA7F',
  '#FFA247',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#F49F15'
17 = '#F0E68C'

[colors.tab_bar]
background = '#3A2521'
inactive_tab_edge = '#2C1512'

[colors.tab_bar.active_tab]
bg_color = '#E87272'
fg_color = '#2F1815'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#4F312B'
fg_color = '#E87272'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#4F312B'
fg_color = '#FFA247'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA247'
fg_color = '#2F1815'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#58B8FD'
fg_color = '#2F1815'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Dark'