# extras/wezterm/oasis_twilight_dark.toml
## name: Oasis Twilight Dark
## author: uhs-robert

[colors]
foreground = "#E6E0F8"
background= "#221B2F"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#221B2F"
selection_bg= "#4D4528"
selection_fg= "#E6E0F8"
split= "#C28EFF"
compose_cursor= "#FFA247"
scrollbar_thumb= "#352D47"
visual_bell= "#2B243B"

ansi = [
  '#101010',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#76665A',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F58B8B'

[colors.tab_bar]
background = '#2B243B'
inactive_tab_edge = '#201C2B'

[colors.tab_bar.active_tab]
bg_color = '#C28EFF'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#352D47'
fg_color = '#C28EFF'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#352D47'
fg_color = '#F2E898'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F2E898'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#6DDFA0'
fg_color = '#221B2F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Twilight Dark'