# extras/wezterm/oasis_night_dark.toml
## name: Oasis Night Dark
## author: uhs-robert

[colors]
foreground = "#F7F4E9"
background= "#0D0D1A"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#0D0D1A"
selection_bg= "#653F73"
selection_fg= "#F7F4E9"
split= "#FF7979"
compose_cursor= "#FF9633"
scrollbar_thumb= "#262633"
visual_bell= "#06060E"

ansi = [
  '#0D0D1A',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#5E5D79',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF9633'
17 = '#F0E68C'

[colors.tab_bar]
background = '#06060E'
inactive_tab_edge = '#0C0C18'

[colors.tab_bar.active_tab]
bg_color = '#FF7979'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#262633'
fg_color = '#FF7979'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#262633'
fg_color = '#F8B471'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F8B471'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#DEC2FF'
fg_color = '#0D0D1A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Dark'