# extras/wezterm/oasis_dune_dark.toml
## name: Oasis Dune Dark
## author: uhs-robert

[colors]
foreground = "#E8E5DA"
background= "#2E2620"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#2E2620"
selection_bg= "#603C6C"
selection_fg= "#2E2620"
split= "#BDB76B"
compose_cursor= "#FFA247"
scrollbar_thumb= "#534A3F"
visual_bell= "#3C332C"

ansi = [
  '#2E2620',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#826D5A',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F29B9B'

[colors.tab_bar]
background = '#3C332C'
inactive_tab_edge = '#2B231E'

[colors.tab_bar.active_tab]
bg_color = '#CDC673'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#534A3F'
fg_color = '#CDC673'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#534A3F'
fg_color = '#AED6B0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#AED6B0'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#D2ADFF'
fg_color = '#2E2620'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Dark'