# extras/wezterm/oasis_desert_dark.toml
## name: Oasis Desert Dark
## author: uhs-robert

[colors]
foreground = "#F7EDE1"
background= "#262626"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#262626"
selection_bg= "#345A2B"
selection_fg= "#262626"
split= "#FF7979"
compose_cursor= "#FF8A1F"
scrollbar_thumb= "#404040"
visual_bell= "#2E2E2E"

ansi = [
  '#262626',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#77725F',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF8A1F'
17 = '#F58B8B'

[colors.tab_bar]
background = '#2E2E2E'
inactive_tab_edge = '#212121'

[colors.tab_bar.active_tab]
bg_color = '#F0E68C'
fg_color = '#262626'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#404040'
fg_color = '#F0E68C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#404040'
fg_color = '#FF7979'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FF7979'
fg_color = '#262626'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#96EA7F'
fg_color = '#262626'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Dark'