# extras/wezterm/oasis_mirage_dark.toml
## name: Oasis Mirage Dark
## author: uhs-robert

[colors]
foreground = "#DDEFEF"
background= "#18252A"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#18252A"
selection_bg= "#5A3824"
selection_fg= "#18252A"
split= "#68C0B6"
compose_cursor= "#FF9633"
scrollbar_thumb= "#2A3F46"
visual_bell= "#1A2D33"

ansi = [
  '#18252A',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#81C0FF',
  '#C695FF',
  '#68C0B6',
  '#DDDBD5',
]

brights = [
  '#587270',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FF9633'
17 = '#F39493'

[colors.tab_bar]
background = '#1A2D33'
inactive_tab_edge = '#172328'

[colors.tab_bar.active_tab]
bg_color = '#79C7BE'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#2A3F46'
fg_color = '#79C7BE'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#2A3F46'
fg_color = '#F8B471'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#F8B471'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#D2ADFF'
fg_color = '#18252A'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Dark'