# extras/wezterm/oasis_cactus_dark.toml
## name: Oasis Cactus Dark
## author: uhs-robert

[colors]
foreground = "#DDF0E5"
background= "#1C261E"
cursor_bg = "#F0E68C"
cursor_border = "#F0E68C"
cursor_fg= "#1C261E"
selection_bg= "#532E2E"
selection_fg= "#DDF0E5"
split= "#7FBB82"
compose_cursor= "#FFA247"
scrollbar_thumb= "#3C4B3E"
visual_bell= "#2C3A30"

ansi = [
  '#101010',
  '#FF7979',
  '#53D390',
  '#F0E68C',
  '#71B8FF',
  '#C28EFF',
  '#5ABAAE',
  '#DDDBD5',
]

brights = [
  '#504641',
  '#FFA0A0',
  '#96EA7F',
  '#F8B471',
  '#87CEEB',
  '#D2ADFF',
  '#8FD1C7',
  '#FFF9F2',
]

[colors.indexed]
16 = '#FFA247'
17 = '#F39493'

[colors.tab_bar]
background = '#2C3A30'
inactive_tab_edge = '#19231B'

[colors.tab_bar.active_tab]
bg_color = '#7FBB82'
fg_color = '#1C261E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#3C4B3E'
fg_color = '#7FBB82'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3C4B3E'
fg_color = '#FFA0A0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#FFA0A0'
fg_color = '#1C261E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#FFC0C0'
fg_color = '#1C261E'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Cactus Dark'