# extras/alacritty/themes/light/2/oasis_midnight_light_2.toml
## name: Oasis Midnight Light 2
## author: uhs-robert

[colors.primary]
background = '#f8eee7'
foreground = '#584f48'

[colors.selection]
background = '#eed5c3'
text = '#584f48'

[colors.cursor]
cursor = '#b22328'
text = '#f8eee7'

[colors.vi_mode_cursor]
cursor = '#884e14'
text = '#f8eee7'

[colors.normal]
black   = '#505050'
red     = '#b91313'
green   = '#2e6749'
yellow  = '#655e22'
blue    = '#155da7'
magenta = '#7b28dc'
cyan    = '#34655f'
white   = '#535048'

[colors.bright]
black   = '#5a4e46'
red     = '#b91313'
green   = '#346826'
yellow  = '#884e14'
blue    = '#24637d'
magenta = '#7929dc'
cyan    = '#33655e'
white   = '#76450c'