# extras/alacritty/themes/light/2/oasis_dune_light_2.toml
## name: Oasis Dune Light 2
## author: uhs-robert

[colors.primary]
background = '#f9f6ec'
foreground = '#57544b'

[colors.selection]
background = '#eee5c9'
text = '#57544b'

[colors.cursor]
cursor = '#686123'
text = '#545454'

[colors.vi_mode_cursor]
cursor = '#914f0e'
text = '#545454'

[colors.normal]
black   = '#545454'
red     = '#a34040'
green   = '#306b4c'
yellow  = '#686123'
blue    = '#155dbe'
magenta = '#7f2fdd'
cyan    = '#366963'
white   = '#57544b'

[colors.bright]
black   = '#545454'
red     = '#c01313'
green   = '#366c27'
yellow  = '#914f0e'
blue    = '#256782'
magenta = '#7e30dd'
cyan    = '#356961'
white   = '#7b480c'