# extras/alacritty/themes/light/2/oasis_twilight_light_2.toml
## name: Oasis Twilight Light 2
## author: uhs-robert

[colors.primary]
background = '#efecf9'
foreground = '#544975'

[colors.selection]
background = '#d2c9ee'
text = '#544975'

[colors.cursor]
cursor = '#7f18e1'
text = '#efecf9'

[colors.vi_mode_cursor]
cursor = '#874d14'
text = '#efecf9'

[colors.normal]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#2e6648'
yellow  = '#635d21'
blue    = '#145ca5'
magenta = '#7925db'
cyan    = '#33645e'
white   = '#524f47'

[colors.bright]
black   = '#564e48'
red     = '#b71212'
green   = '#346725'
yellow  = '#874d14'
blue    = '#23627b'
magenta = '#7827db'
cyan    = '#33645c'
white   = '#75440b'