# extras/alacritty/themes/light/2/oasis_lagoon_light_2.toml
## name: Oasis Lagoon Light 2
## author: uhs-robert

[colors.primary]
background = '#ebf1f9'
foreground = '#3d5273'

[colors.selection]
background = '#c8d8ee'
text = '#3d5273'

[colors.cursor]
cursor = '#135fa2'
text = '#ebf1f9'

[colors.vi_mode_cursor]
cursor = '#894f14'
text = '#ebf1f9'

[colors.normal]
black   = '#515151'
red     = '#ba1313'
green   = '#2f6849'
yellow  = '#655e22'
blue    = '#155ea8'
magenta = '#7b29dc'
cyan    = '#34655f'
white   = '#535148'

[colors.bright]
black   = '#5b4f47'
red     = '#ba1313'
green   = '#346926'
yellow  = '#894f14'
blue    = '#24647e'
magenta = '#7a2adc'
cyan    = '#34655e'
white   = '#77450c'