# extras/alacritty/themes/light/2/oasis_cactus_light_2.toml
## name: Oasis Cactus Light 2
## author: uhs-robert

[colors.primary]
background = '#eef7f2'
foreground = '#44584c'

[colors.selection]
background = '#cfe8da'
text = '#44584c'

[colors.cursor]
cursor = '#3e6940'
text = '#eef7f2'

[colors.vi_mode_cursor]
cursor = '#8d5115'
text = '#eef7f2'

[colors.normal]
black   = '#535353'
red     = '#bf1313'
green   = '#306b4b'
yellow  = '#686123'
blue    = '#1560ad'
magenta = '#7e2ddc'
cyan    = '#356862'
white   = '#56534b'

[colors.bright]
black   = '#5a524c'
red     = '#bf1313'
green   = '#366b27'
yellow  = '#8d5115'
blue    = '#256681'
magenta = '#7d2fdd'
cyan    = '#356861'
white   = '#7a470c'