# extras/alacritty/themes/light/2/oasis_lagoon_light_2.toml
## name: Oasis Lagoon Light 2
## author: uhs-robert

[colors.primary]
background = '#ebf1f9'
foreground = '#3d5273'

[colors.selection]
background = '#c8d8ee'
text = '#3d5273'

[colors.cursor]
cursor = '#655e22'
text = '#515151'

[colors.vi_mode_cursor]
cursor = '#8d4d0e'
text = '#515151'

[colors.normal]
black   = '#515151'
red     = '#9d3d3d'
green   = '#2f6849'
yellow  = '#655e22'
blue    = '#145ab8'
magenta = '#7b28dc'
cyan    = '#346560'
white   = '#535148'

[colors.bright]
black   = '#515151'
red     = '#ba1313'
green   = '#346926'
yellow  = '#8d4d0e'
blue    = '#24647e'
magenta = '#7a2adc'
cyan    = '#34655e'
white   = '#77450c'