# extras/alacritty/themes/light/2/oasis_sol_light_2.toml
## name: Oasis Sol Light 2
## author: uhs-robert

[colors.primary]
background = '#f8eae7'
foreground = '#793e33'

[colors.selection]
background = '#eecbc3'
text = '#793e33'

[colors.cursor]
cursor = '#ad262a'
text = '#f8eae7'

[colors.vi_mode_cursor]
cursor = '#864d14'
text = '#f8eae7'

[colors.normal]
black   = '#4f4f4f'
red     = '#b61212'
green   = '#2d6548'
yellow  = '#635c21'
blue    = '#145ca4'
magenta = '#7824dc'
cyan    = '#33635e'
white   = '#524f47'

[colors.bright]
black   = '#554d48'
red     = '#b61212'
green   = '#336625'
yellow  = '#864d14'
blue    = '#23627b'
magenta = '#7826db'
cyan    = '#33635c'
white   = '#74430b'