# extras/alacritty/themes/light/2/oasis_cactus_light_2.toml
## name: Oasis Cactus Light 2
## author: uhs-robert

[colors.primary]
background = '#eef7f2'
foreground = '#44584c'

[colors.selection]
background = '#cfe8da'
text = '#44584c'

[colors.cursor]
cursor = '#686123'
text = '#535353'

[colors.vi_mode_cursor]
cursor = '#904f0e'
text = '#535353'

[colors.normal]
black   = '#535353'
red     = '#a13f3f'
green   = '#306b4b'
yellow  = '#686123'
blue    = '#145dbd'
magenta = '#7e2ddd'
cyan    = '#366863'
white   = '#56534b'

[colors.bright]
black   = '#535353'
red     = '#bf1313'
green   = '#366b27'
yellow  = '#904f0e'
blue    = '#256681'
magenta = '#7d2fdd'
cyan    = '#356861'
white   = '#7a470c'