# extras/alacritty/themes/light/2/oasis_rose_light_2.toml
## name: Oasis Rose Light 2
## author: uhs-robert

[colors.primary]
background = '#f9ecf5'
foreground = '#61495c'

[colors.selection]
background = '#eec9e3'
text = '#61495c'

[colors.cursor]
cursor = '#b8141b'
text = '#f9ecf5'

[colors.vi_mode_cursor]
cursor = '#884e14'
text = '#f9ecf5'

[colors.normal]
black   = '#505050'
red     = '#b91313'
green   = '#2e6749'
yellow  = '#645e22'
blue    = '#145da7'
magenta = '#7a28db'
cyan    = '#34655f'
white   = '#535048'

[colors.bright]
black   = '#574f49'
red     = '#b91313'
green   = '#346826'
yellow  = '#884e14'
blue    = '#24637d'
magenta = '#7929dc'
cyan    = '#33655e'
white   = '#76450c'