# extras/alacritty/themes/light/2/oasis_twilight_light_2.toml
## name: Oasis Twilight Light 2
## author: uhs-robert

[colors.primary]
background = '#efecf9'
foreground = '#544975'

[colors.selection]
background = '#d2c9ee'
text = '#544975'

[colors.cursor]
cursor = '#635d21'
text = '#4f4f4f'

[colors.vi_mode_cursor]
cursor = '#8a4c0d'
text = '#4f4f4f'

[colors.normal]
black   = '#4f4f4f'
red     = '#9b3d3d'
green   = '#2e6648'
yellow  = '#635d21'
blue    = '#1459b5'
magenta = '#7925dc'
cyan    = '#33645e'
white   = '#524f47'

[colors.bright]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#346725'
yellow  = '#8a4c0d'
blue    = '#23627b'
magenta = '#7827db'
cyan    = '#33645c'
white   = '#75440b'