# extras/alacritty/themes/light/2/oasis_dune_light_2.toml
## name: Oasis Dune Light 2
## author: uhs-robert

[colors.primary]
background = '#f9f6ec'
foreground = '#57544b'

[colors.selection]
background = '#eee5c9'
text = '#57544b'

[colors.cursor]
cursor = '#6b611a'
text = '#f9f6ec'

[colors.vi_mode_cursor]
cursor = '#8e5115'
text = '#f9f6ec'

[colors.normal]
black   = '#545454'
red     = '#b72929'
green   = '#306b4c'
yellow  = '#696220'
blue    = '#1561ad'
magenta = '#7f2fdd'
cyan    = '#366963'
white   = '#57544b'

[colors.bright]
black   = '#5b534c'
red     = '#c01313'
green   = '#366c27'
yellow  = '#8e5115'
blue    = '#256782'
magenta = '#7e30dd'
cyan    = '#356961'
white   = '#7b480c'