# extras/alacritty/themes/light/2/oasis_rose_light_2.toml
## name: Oasis Rose Light 2
## author: uhs-robert

[colors.primary]
background = '#f9ecf5'
foreground = '#61495c'

[colors.selection]
background = '#eec9e3'
text = '#61495c'

[colors.cursor]
cursor = '#645e22'
text = '#505050'

[colors.vi_mode_cursor]
cursor = '#8c4c0e'
text = '#505050'

[colors.normal]
black   = '#505050'
red     = '#9c3d3d'
green   = '#2e6749'
yellow  = '#645e22'
blue    = '#145ab7'
magenta = '#7b27dc'
cyan    = '#34655f'
white   = '#535048'

[colors.bright]
black   = '#505050'
red     = '#b91313'
green   = '#346826'
yellow  = '#8c4c0e'
blue    = '#24637d'
magenta = '#7929dc'
cyan    = '#33655e'
white   = '#76450c'