# extras/alacritty/themes/light/2/oasis_starlight_light_2.toml
## name: Oasis Starlight Light 2
## author: uhs-robert

[colors.primary]
background = '#f9f5ec'
foreground = '#5b5341'

[colors.selection]
background = '#eee3c9'
text = '#5b5341'

[colors.cursor]
cursor = '#1462a7'
text = '#f9f5ec'

[colors.vi_mode_cursor]
cursor = '#8d5115'
text = '#f9f5ec'

[colors.normal]
black   = '#545454'
red     = '#a23f3f'
green   = '#306b4b'
yellow  = '#686123'
blue    = '#145dbd'
magenta = '#7e2edd'
cyan    = '#366863'
white   = '#56544b'

[colors.bright]
black   = '#5a524c'
red     = '#bf1313'
green   = '#366c27'
yellow  = '#8d5115'
blue    = '#256781'
magenta = '#7d2fdd'
cyan    = '#356961'
white   = '#7a470c'