# extras/alacritty/themes/light/2/oasis_mirage_light_2.toml
## name: Oasis Mirage Light 2
## author: uhs-robert

[colors.primary]
background = '#ebf9f9'
foreground = '#425858'

[colors.selection]
background = '#c8eeee'
text = '#425858'

[colors.cursor]
cursor = '#356962'
text = '#ebf9f9'

[colors.vi_mode_cursor]
cursor = '#8e5115'
text = '#ebf9f9'

[colors.normal]
black   = '#545454'
red     = '#c01313'
green   = '#306b4c'
yellow  = '#686123'
blue    = '#1561ad'
magenta = '#7f2fdd'
cyan    = '#366963'
white   = '#57544b'

[colors.bright]
black   = '#5b534c'
red     = '#c01313'
green   = '#366d27'
yellow  = '#8e5115'
blue    = '#256782'
magenta = '#7e30dd'
cyan    = '#356961'
white   = '#7b480c'