# extras/alacritty/themes/light/2/oasis_night_light_2.toml
## name: Oasis Night Light 2
## author: uhs-robert

[colors.primary]
background = '#e9deb9'
foreground = '#54432d'

[colors.selection]
background = '#decd96'
text = '#54432d'

[colors.cursor]
cursor = '#7e430e'
text = '#e9deb9'

[colors.vi_mode_cursor]
cursor = '#794512'
text = '#e9deb9'

[colors.normal]
black   = '#464646'
red     = '#a51111'
green   = '#295c41'
yellow  = '#59531e'
blue    = '#125395'
magenta = '#6d21c7'
cyan    = '#2e5954'
white   = '#48463f'

[colors.bright]
black   = '#4c4540'
red     = '#a51111'
green   = '#2e5c22'
yellow  = '#794512'
blue    = '#20586f'
magenta = '#6c21c8'
cyan    = '#2e5a53'
white   = '#673c0a'