# extras/alacritty/themes/light/2/oasis_desert_light_2.toml
## name: Oasis Desert Light 2
## author: uhs-robert

[colors.primary]
background = '#f8f0e7'
foreground = '#5f4e3b'

[colors.selection]
background = '#eedac3'
text = '#5f4e3b'

[colors.cursor]
cursor = '#695e19'
text = '#f8f0e7'

[colors.vi_mode_cursor]
cursor = '#8a4f14'
text = '#f8f0e7'

[colors.normal]
black   = '#515151'
red     = '#bb1313'
green   = '#2f6849'
yellow  = '#655f22'
blue    = '#155ea8'
magenta = '#7c29dc'
cyan    = '#356660'
white   = '#545149'

[colors.bright]
black   = '#58504a'
red     = '#bb1313'
green   = '#356926'
yellow  = '#8a4f14'
blue    = '#24647e'
magenta = '#7a2bdc'
cyan    = '#34665f'
white   = '#77450c'