# extras/alacritty/themes/dark/oasis_rose_dark.toml
## name: Oasis Rose Dark
## author: uhs-robert

[colors.primary]
background = '#301828'
foreground = '#EDD5E7'

[colors.selection]
background = '#523A4B'
text = '#EDD5E7'

[colors.cursor]
cursor = '#F0E68C'
text = '#301828'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#301828'

[colors.normal]
black   = '#101010'
red     = '#D06666'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#519BFF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'