# extras/alacritty/themes/dark/oasis_midnight_dark.toml
## name: Oasis Midnight Dark
## author: uhs-robert

[colors.primary]
background = '#101418'
foreground = '#F7F4F2'

[colors.selection]
background = '#1C242C'
text = '#F7F4F2'

[colors.cursor]
cursor = '#F0E68C'
text = '#101418'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#101418'

[colors.normal]
black   = '#101010'
red     = '#FF7979'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#71B8FF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'