# extras/alacritty/themes/dark/oasis_lagoon_dark.toml
## name: Oasis Lagoon Dark
## author: uhs-robert

[colors.primary]
background = '#101825'
foreground = '#D9E6FA'

[colors.selection]
background = '#22385C'
text = '#D9E6FA'

[colors.cursor]
cursor = '#F0E68C'
text = '#101825'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#101825'

[colors.normal]
black   = '#101825'
red     = '#FF7979'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#81C0FF'
magenta = '#C695FF'
cyan    = '#68C0B6'
white   = '#DDDBD5'

[colors.bright]
black   = '#3B6A87'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'