# extras/alacritty/themes/dark/oasis_desert_dark.toml
## name: Oasis Desert Dark
## author: uhs-robert

[colors.primary]
background = '#262626'
foreground = '#F7EDE1'

[colors.selection]
background = '#433F38'
text = '#F7EDE1'

[colors.cursor]
cursor = '#F0E68C'
text = '#262626'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#262626'

[colors.normal]
black   = '#262626'
red     = '#FF7979'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#81C0FF'
magenta = '#C695FF'
cyan    = '#68C0B6'
white   = '#DDDBD5'

[colors.bright]
black   = '#77725F'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'