# extras/alacritty/themes/dark/oasis_canyon_dark.toml
## name: Oasis Canyon Dark
## author: uhs-robert

[colors.primary]
background = '#2F1A05'
foreground = '#F8E7D3'

[colors.selection]
background = '#624020'
text = '#F8E7D3'

[colors.cursor]
cursor = '#F0E68C'
text = '#2F1A05'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#2F1A05'

[colors.normal]
black   = '#101010'
red     = '#ED7777'
green   = '#53D390'
yellow  = '#F3E989'
blue    = '#71B8FF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'