# extras/alacritty/themes/dark/oasis_night_dark.toml
## name: Oasis Night Dark
## author: uhs-robert

[colors.primary]
background = '#0D0D1A'
foreground = '#F7F4E9'

[colors.selection]
background = '#3E2F4A'
text = '#F7F4E9'

[colors.cursor]
cursor = '#F0E68C'
text = '#0D0D1A'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#0D0D1A'

[colors.normal]
black   = '#101010'
red     = '#FF7979'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#81C0FF'
magenta = '#C695FF'
cyan    = '#68C0B6'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'