# extras/alacritty/themes/dark/oasis_twilight_dark.toml
## name: Oasis Twilight Dark
## author: uhs-robert

[colors.primary]
background = '#221B2F'
foreground = '#E6E0F8'

[colors.selection]
background = '#352D47'
text = '#E6E0F8'

[colors.cursor]
cursor = '#F0E68C'
text = '#221B2F'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#221B2F'

[colors.normal]
black   = '#101010'
red     = '#ED7777'
green   = '#53D390'
yellow  = '#F3E989'
blue    = '#71B8FF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'