# extras/alacritty/themes/dark/oasis_dune_dark.toml
## name: Oasis Dune Dark
## author: uhs-robert

[colors.primary]
background = '#2E2620'
foreground = '#E8E5DA'

[colors.selection]
background = '#534A3F'
text = '#E8E5DA'

[colors.cursor]
cursor = '#F0E68C'
text = '#2E2620'

[colors.vi_mode_cursor]
cursor = '#F8B471'
text = '#2E2620'

[colors.normal]
black   = '#101010'
red     = '#FF7979'
green   = '#53D390'
yellow  = '#F0E68C'
blue    = '#71B8FF'
magenta = '#C28EFF'
cyan    = '#5ABAAE'
white   = '#DDDBD5'

[colors.bright]
black   = '#504641'
red     = '#FFA0A0'
green   = '#96EA7F'
yellow  = '#F8B471'
blue    = '#87CEEB'
magenta = '#D2ADFF'
cyan    = '#8FD1C7'
white   = '#FFF9F2'