# extras/alacritty/themes/desert_light_1/oasis_desert_light_1.toml
## name: Oasis Desert Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f7f5'
foreground = '#63523d'

[colors.selection]
background = '#e8e0d8'
text = '#63523d'

[colors.cursor]
cursor = '#696223'
text = '#555555'

[colors.vi_mode_cursor]
cursor = '#93500e'
text = '#555555'

[colors.normal]
black   = '#555555'
red     = '#a44040'
green   = '#306c4c'
yellow  = '#696223'
blue    = '#155ec0'
magenta = '#7f30dd'
cyan    = '#376a62'
white   = '#58554c'

[colors.bright]
black   = '#555555'
red     = '#c21313'
green   = '#366d27'
yellow  = '#93500e'
blue    = '#266884'
magenta = '#7f31de'
cyan    = '#356a62'
white   = '#7d490c'