# extras/alacritty/themes/desert_light_2/oasis_desert_light_2.toml
## name: Oasis Desert Light 2
## author: uhs-robert

[colors.primary]
background = '#f8f0e7'
foreground = '#5f4e3b'

[colors.selection]
background = '#eedac3'
text = '#5f4e3b'

[colors.cursor]
cursor = '#655f22'
text = '#515151'

[colors.vi_mode_cursor]
cursor = '#8d4d0e'
text = '#515151'

[colors.normal]
black   = '#515151'
red     = '#9e3e3e'
green   = '#2f6849'
yellow  = '#655f22'
blue    = '#145bb9'
magenta = '#7c29dc'
cyan    = '#356660'
white   = '#545149'

[colors.bright]
black   = '#515151'
red     = '#bb1313'
green   = '#356926'
yellow  = '#8d4d0e'
blue    = '#24647e'
magenta = '#7a2bdc'
cyan    = '#34665f'
white   = '#77450c'