# extras/alacritty/themes/desert_light_3/oasis_desert_light_3.toml
## name: Oasis Desert Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e6d4'
foreground = '#514c47'

[colors.selection]
background = '#f0d0ad'
text = '#514c47'

[colors.cursor]
cursor = '#605920'
text = '#4c4c4c'

[colors.vi_mode_cursor]
cursor = '#86490d'
text = '#4c4c4c'

[colors.normal]
black   = '#4c4c4c'
red     = '#953b3b'
green   = '#2c6346'
yellow  = '#605920'
blue    = '#1356b0'
magenta = '#7523d6'
cyan    = '#32605b'
white   = '#4f4c45'

[colors.bright]
black   = '#4c4c4c'
red     = '#b11212'
green   = '#326424'
yellow  = '#86490d'
blue    = '#225f77'
magenta = '#7423d7'
cyan    = '#31605a'
white   = '#70410b'