# extras/alacritty/themes/desert_light_4/oasis_desert_light_4.toml
## name: Oasis Desert Light 4
## author: uhs-robert

[colors.primary]
background = '#f5ddc7'
foreground = '#4c4742'

[colors.selection]
background = '#eec5a0'
text = '#4c4742'

[colors.cursor]
cursor = '#5b551f'
text = '#484848'

[colors.vi_mode_cursor]
cursor = '#7f450d'
text = '#484848'

[colors.normal]
black   = '#484848'
red     = '#8e3838'
green   = '#2a5e42'
yellow  = '#5b551f'
blue    = '#1251a6'
magenta = '#7021cc'
cyan    = '#2f5b55'
white   = '#4a4841'

[colors.bright]
black   = '#484848'
red     = '#a91010'
green   = '#305e23'
yellow  = '#7f450d'
blue    = '#205a71'
magenta = '#6f21cd'
cyan    = '#2f5c55'
white   = '#693e0b'