# extras/wezterm/oasis_sol_light_5.toml
## name: Oasis Sol Light 5
## author: uhs-robert

[colors]
foreground = "#5b2e26"
background= "#f3bfba"
cursor_bg = "#871f20"
cursor_border = "#871f20"
cursor_fg= "#f3bfba"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#701b1b"
compose_cursor= "#543314"
scrollbar_thumb= "#ec9b93"
visual_bell= "#f1b3ad"

ansi = [
  '#3a3a3a',
  '#8f0e0e',
  '#234f38',
  '#4c4719',
  '#0f477f',
  '#5e1cab',
  '#274d48',
  '#3c3a34',
]

brights = [
  '#413932',
  '#8f0e0e',
  '#274f1d',
  '#683b0f',
  '#1b4b5f',
  '#5d1cac',
  '#274d47',
  '#563209',
]

[colors.indexed]
16 = '#543314'
17 = '#4e4713'

[colors.tab_bar]
background = '#f1b3ad'
inactive_tab_edge = '#eea7a0'

[colors.tab_bar.active_tab]
bg_color = '#800000'
fg_color = '#f3bfba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ec9b93'
fg_color = '#800000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ec9b93'
fg_color = '#834406'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#834406'
fg_color = '#f3bfba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#014e88'
fg_color = '#f3bfba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Sol Light 5'