# extras/wezterm/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors]
foreground = "#4a4940"
background= "#ece1c6"
cursor_bg= "#5e5517"
cursor_border= "#5e5517"
cursor_fg= "#e8dbbb"
selection_bg= "#e1cfa4"
selection_fg= "#e8dbbb"
split= "#4b4934"
compose_cursor= "#673f19"
scrollbar_thumb= "#e1cfa4"
visual_bell= "#e8dbbb"

ansi = [
  '#484848',
  '#8f3838',
  '#2a5e42',
  '#5b551e',
  '#1352a8',
  '#7121cc',
  '#305c56',
  '#4a4841',
]

brights = [
  '#484848',
  '#aa1111',
  '#2f5f22',
  '#80460d',
  '#215b72',
  '#6f22cd',
  '#2f5c55',
  '#6a3e0b',
]

[colors.indexed]
16 = '#673f19'
17 = '#9f272b'

[colors.tab_bar]
background = '#e8dbbb'
inactive_tab_edge = '#e4d5af'

[colors.tab_bar.active_tab]
bg_color = '#585527'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e1cfa4'
fg_color = '#4a4940'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8dbbb'
fg_color = '#4a4940'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2e5c30'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1c6e43'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 5'