# extras/wezterm/oasis_lagoon_light_5.toml
## name: Oasis Lagoon Light 5
## author: uhs-robert

[colors]
foreground = "#30405b"
background= "#bcd6f5"
cursor_bg = "#104d84"
cursor_border = "#104d84"
cursor_fg= "#bcd6f5"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#1a435f"
compose_cursor= "#5b3716"
scrollbar_thumb= "#94beef"
visual_bell= "#afcef3"

ansi = [
  '#404040',
  '#803232',
  '#26543c',
  '#524d1b',
  '#114997',
  '#651eb8',
  '#2b524d',
  '#413f39',
]

brights = [
  '#404040',
  '#990f0f',
  '#2a551f',
  '#733e0b',
  '#1d5166',
  '#641eb8',
  '#2a534c',
  '#5d3609',
]

[colors.indexed]
16 = '#5b3716'
17 = '#931d20'

[colors.tab_bar]
background = '#afcef3'
inactive_tab_edge = '#a1c6f1'

[colors.tab_bar.active_tab]
bg_color = '#014b7e'
fg_color = '#bcd6f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#94beef'
fg_color = '#014b7e'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#94beef'
fg_color = '#8a4400'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8a4400'
fg_color = '#bcd6f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#8a0000'
fg_color = '#bcd6f5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Lagoon Light 5'