# extras/wezterm/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors]
foreground = "#4a4940"
background= "#ece1c6"
cursor_bg = "#5e5517"
cursor_border = "#5e5517"
cursor_fg= "#ece1c6"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#4b4934"
compose_cursor= "#683f19"
scrollbar_thumb= "#e1cfa4"
visual_bell= "#e8dbbb"

ansi = [
  '#484848',
  '#a91010',
  '#2a5e42',
  '#5b551e',
  '#125597',
  '#7021cc',
  '#2f5c57',
  '#4a4841',
]

brights = [
  '#50473e',
  '#aa1111',
  '#2f5f22',
  '#7d4712',
  '#215b72',
  '#6f22cd',
  '#2f5c55',
  '#6a3e0b',
]

[colors.indexed]
16 = '#683f19'
17 = '#9f272b'

[colors.tab_bar]
background = '#e8dbbb'
inactive_tab_edge = '#e4d5af'

[colors.tab_bar.active_tab]
bg_color = '#71670f'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e1cfa4'
fg_color = '#71670f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e1cfa4'
fg_color = '#286259'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#286259'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#ece1c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 5'