# extras/wezterm/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors]
foreground = "#4b3b28"
background= "#e0cfa3"
cursor_bg = "#723b0c"
cursor_border = "#723b0c"
cursor_fg= "#e0cfa3"
selection_bg= "#e1b69d"
selection_fg= "#4e260e"
split= "#751c1c"
compose_cursor= "#583515"
scrollbar_thumb= "#d5bd81"
visual_bell= "#ddc998"

ansi = [
  '#583512',
  '#950e0e',
  '#24523a',
  '#504b1a',
  '#104b84',
  '#621db3',
  '#29504b',
  '#3f3d37',
]

brights = [
  '#4e392c',
  '#950e0e',
  '#29531e',
  '#6d3e10',
  '#1d4f63',
  '#621eb4',
  '#29504a',
  '#5a3509',
]

[colors.indexed]
16 = '#583515'
17 = '#8f1c20'

[colors.tab_bar]
background = '#ddc998'
inactive_tab_edge = '#d9c38c'

[colors.tab_bar.active_tab]
bg_color = '#800000'
fg_color = '#e0cfa3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#d5bd81'
fg_color = '#800000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d5bd81'
fg_color = '#834406'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#834406'
fg_color = '#e0cfa3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3f008a'
fg_color = '#e0cfa3'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Night Light 5'