# extras/wezterm/oasis_abyss_light_5.toml
## name: Oasis Abyss Light 5
## author: uhs-robert

[colors]
foreground = "#48413b"
background= "#f3d2ba"
cursor_bg = "#981e22"
cursor_border = "#981e22"
cursor_fg= "#f3d2ba"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#742a2a"
compose_cursor= "#5f3a17"
scrollbar_thumb= "#ecb893"
visual_bell= "#f1c9ad"

ansi = [
  '#424242',
  '#962222',
  '#27583e',
  '#55501a',
  '#124f8e',
  '#691fbe',
  '#2c5550',
  '#45433c',
]

brights = [
  '#48413d',
  '#9e0f0f',
  '#2c5920',
  '#744211',
  '#1e546a',
  '#681fbf',
  '#2b564f',
  '#62390a',
]

[colors.indexed]
16 = '#5f3a17'
17 = '#554f27'

[colors.tab_bar]
background = '#f1c9ad'
inactive_tab_edge = '#eec1a0'

[colors.tab_bar.active_tab]
bg_color = '#710f0f'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecb893'
fg_color = '#710f0f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ecb893'
fg_color = '#834406'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#834406'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2e5c55'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 5'