# extras/wezterm/oasis_starlight_light_5.toml
## name: Oasis Starlight Light 5
## author: uhs-robert

[colors]
foreground = "#4d4738"
background= "#f3deba"
cursor_bg = "#125592"
cursor_border = "#125592"
cursor_fg= "#f3deba"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#1d4b6b"
compose_cursor= "#663f19"
scrollbar_thumb= "#eccb93"
visual_bell= "#f1d8ad"

ansi = [
  '#474747',
  '#a81010',
  '#2a5d42',
  '#5b551e',
  '#125596',
  '#6f21ca',
  '#2f5b56',
  '#4a4740',
]

brights = [
  '#4f463d',
  '#a81010',
  '#2f5e22',
  '#7c4712',
  '#205a71',
  '#6e21cb',
  '#2e5b54',
  '#693d0b',
]

[colors.indexed]
16 = '#663f19'
17 = '#a81218'

[colors.tab_bar]
background = '#f1d8ad'
inactive_tab_edge = '#eed2a0'

[colors.tab_bar.active_tab]
bg_color = '#024a7e'
fg_color = '#f3deba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eccb93'
fg_color = '#024a7e'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#eccb93'
fg_color = '#7a6f10'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#7a6f10'
fg_color = '#f3deba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#834406'
fg_color = '#f3deba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Starlight Light 5'