# extras/wezterm/oasis_abyss_light_5.toml
## name: Oasis Abyss Light 5
## author: uhs-robert

[colors]
foreground = "#48413b"
background= "#f3d2ba"
cursor_bg= "#981e22"
cursor_border= "#981e22"
cursor_fg= "#f1c9ad"
selection_bg= "#ecb893"
selection_fg= "#f1c9ad"
split= "#6f2e2e"
compose_cursor= "#5f3a17"
scrollbar_thumb= "#ecb893"
visual_bell= "#f1c9ad"

ansi = [
  '#424242',
  '#853434',
  '#27583e',
  '#554f1c',
  '#124c9c',
  '#691fbe',
  '#2c5550',
  '#45433c',
]

brights = [
  '#424242',
  '#9e0f0f',
  '#2c5920',
  '#77410c',
  '#1e546a',
  '#681fbf',
  '#2b564f',
  '#62390a',
]

[colors.indexed]
16 = '#5f3a17'
17 = '#554f27'

[colors.tab_bar]
background = '#f1c9ad'
inactive_tab_edge = '#eec1a0'

[colors.tab_bar.active_tab]
bg_color = '#621e1e'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecb893'
fg_color = '#48413b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f1c9ad'
fg_color = '#48413b'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8a4400'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#2e5c55'
fg_color = '#f3d2ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Abyss Light 5'