# extras/wezterm/oasis_mirage_light_5.toml
## name: Oasis Mirage Light 5
## author: uhs-robert

[colors]
foreground = "#3c5050"
background= "#c0f2ee"
cursor_bg = "#31605a"
cursor_border = "#31605a"
cursor_fg= "#c0f2ee"
selection_bg= "#9fe0d7"
selection_fg= "#0f4c44"
split= "#32524e"
compose_cursor= "#6c431a"
scrollbar_thumb= "#9aeae4"
visual_bell= "#b3efeb"

ansi = [
  '#4c4c4c',
  '#b11111',
  '#2c6346',
  '#605a20',
  '#13599f',
  '#7523d5',
  '#31605b',
  '#4e4c44',
]

brights = [
  '#554a41',
  '#b11111',
  '#316424',
  '#834b13',
  '#225f77',
  '#7423d6',
  '#316159',
  '#70410b',
]

[colors.indexed]
16 = '#6c431a'
17 = '#a82628'

[colors.tab_bar]
background = '#b3efeb'
inactive_tab_edge = '#a7ede7'

[colors.tab_bar.active_tab]
bg_color = '#265a54'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#9aeae4'
fg_color = '#265a54'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#9aeae4'
fg_color = '#834406'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#834406'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e008a'
fg_color = '#c0f2ee'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Mirage Light 5'