# extras/wezterm/oasis_desert_light_5.toml
## name: Oasis Desert Light 5
## author: uhs-robert

[colors]
foreground = "#504132"
background= "#f3d5ba"
cursor_bg = "#595016"
cursor_border = "#595016"
cursor_fg= "#f3d5ba"
selection_bg= "#dacfa4"
selection_fg= "#473c15"
split= "#811f1f"
compose_cursor= "#613b18"
scrollbar_thumb= "#ecbd93"
visual_bell= "#f1cdad"

ansi = [
  '#444444',
  '#a11010',
  '#28593f',
  '#56511d',
  '#11518f',
  '#6b1fc2',
  '#2d5752',
  '#46443d',
]

brights = [
  '#4b423a',
  '#a11010',
  '#2d5a20',
  '#764311',
  '#1f566c',
  '#6a20c2',
  '#2c5750',
  '#643a0a',
]

[colors.indexed]
16 = '#613b18'
17 = '#9b1e22'

[colors.tab_bar]
background = '#f1cdad'
inactive_tab_edge = '#eec5a0'

[colors.tab_bar.active_tab]
bg_color = '#71670f'
fg_color = '#f3d5ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecbd93'
fg_color = '#71670f'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ecbd93'
fg_color = '#8a0000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#8a0000'
fg_color = '#f3d5ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#297613'
fg_color = '#f3d5ba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Desert Light 5'