# extras/wezterm/oasis_midnight_light_5.toml
## name: Oasis Midnight Light 5
## author: uhs-robert

[colors]
foreground = "#473f3a"
background= "#f3cdba"
cursor_bg = "#941d21"
cursor_border = "#941d21"
cursor_fg= "#f3cdba"
selection_bg= "#e19d9d"
selection_fg= "#4e0e0e"
split= "#7a1e1e"
compose_cursor= "#5b3816"
scrollbar_thumb= "#ecb193"
visual_bell= "#f1c4ad"

ansi = [
  '#404040',
  '#9a0f0f',
  '#26553c',
  '#534d1b',
  '#114d89',
  '#661eb9',
  '#2b534e',
  '#42403a',
]

brights = [
  '#463f3b',
  '#9a0f0f',
  '#2b561f',
  '#714011',
  '#1e5267',
  '#651fba',
  '#2a534d',
  '#5f370a',
]

[colors.indexed]
16 = '#5b3816'
17 = '#554d15'

[colors.tab_bar]
background = '#f1c4ad'
inactive_tab_edge = '#eebaa0'

[colors.tab_bar.active_tab]
bg_color = '#800000'
fg_color = '#f3cdba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#ecb193'
fg_color = '#800000'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ecb193'
fg_color = '#834406'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#834406'
fg_color = '#f3cdba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#286259'
fg_color = '#f3cdba'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Midnight Light 5'