# extras/alacritty/themes/dust/oasis_dust.toml
## name: Oasis Dust
## author: uhs-robert

[colors.primary]
background = '#D4B165'
foreground = '#181309'

[colors.selection]
background = '#C39E4F'
text = '#181309'

[colors.cursor]
cursor = '#3c3814'
text = '#2a2a2a'

[colors.vi_mode_cursor]
cursor = '#542e08'
text = '#2a2a2a'

[colors.normal]
black   = '#2a2a2a'
red     = '#5f2525'
green   = '#1c3e2c'
yellow  = '#3c3814'
blue    = '#0c366e'
magenta = '#4b1688'
cyan    = '#1f3c39'
white   = '#2c2a26'

[colors.bright]
black   = '#2a2a2a'
red     = '#720c0c'
green   = '#1f3f17'
yellow  = '#542e08'
blue    = '#163c4b'
magenta = '#4a1789'
cyan    = '#1f3c38'
white   = '#3f2406'