# extras/alacritty/themes/abyss_light_3/oasis_abyss_light_3.toml
## name: Oasis Abyss Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e5d4'
foreground = '#524b43'

[colors.selection]
background = '#f0cead'
text = '#524b43'

[colors.cursor]
cursor = '#605920'
text = '#4c4c4c'

[colors.vi_mode_cursor]
cursor = '#85490d'
text = '#4c4c4c'

[colors.normal]
black   = '#4c4c4c'
red     = '#953a3a'
green   = '#2c6245'
yellow  = '#605920'
blue    = '#1355af'
magenta = '#7523d5'
cyan    = '#32605a'
white   = '#4f4c44'

[colors.bright]
black   = '#4c4c4c'
red     = '#b01212'
green   = '#326324'
yellow  = '#85490d'
blue    = '#225f77'
magenta = '#7423d6'
cyan    = '#316059'
white   = '#70410b'