# extras/alacritty/themes/abyss_light_5/oasis_abyss_light_5.toml
## name: Oasis Abyss Light 5
## author: uhs-robert

[colors.primary]
background = '#f3c1ba'
foreground = '#433936'

[colors.selection]
background = '#ec9e93'
text = '#433936'

[colors.cursor]
cursor = '#4d481a'
text = '#3b3b3b'

[colors.vi_mode_cursor]
cursor = '#6c3b0b'
text = '#3b3b3b'

[colors.normal]
black   = '#3b3b3b'
red     = '#793030'
green   = '#235038'
yellow  = '#4d481a'
blue    = '#10458e'
magenta = '#601cad'
cyan    = '#284d49'
white   = '#3d3b35'

[colors.bright]
black   = '#3b3b3b'
red     = '#910e0e'
green   = '#28501d'
yellow  = '#6c3b0b'
blue    = '#1c4c60'
magenta = '#5f1dae'
cyan    = '#274e48'
white   = '#573309'