# extras/alacritty/themes/abyss_light_4/oasis_abyss_light_4.toml
## name: Oasis Abyss Light 4
## author: uhs-robert

[colors.primary]
background = '#f5cfc7'
foreground = '#4a403c'

[colors.selection]
background = '#eeaea0'
text = '#4a403c'

[colors.cursor]
cursor = '#554f1c'
text = '#424242'

[colors.vi_mode_cursor]
cursor = '#76400c'
text = '#424242'

[colors.normal]
black   = '#424242'
red     = '#843434'
green   = '#27573e'
yellow  = '#554f1c'
blue    = '#114c9b'
magenta = '#681fbe'
cyan    = '#2c5550'
white   = '#44423b'

[colors.bright]
black   = '#424242'
red     = '#9e0f0f'
green   = '#2c5820'
yellow  = '#76400c'
blue    = '#1e5469'
magenta = '#671fbf'
cyan    = '#2b554f'
white   = '#61390a'