# extras/alacritty/themes/abyss_light_5/oasis_abyss_light_5.toml
## name: Oasis Abyss Light 5
## author: uhs-robert

[colors.primary]
background = '#f3d2ba'
foreground = '#48413b'

[colors.selection]
background = '#ecb893'
text = '#48413b'

[colors.cursor]
cursor = '#554f1c'
text = '#424242'

[colors.vi_mode_cursor]
cursor = '#77410c'
text = '#424242'

[colors.normal]
black   = '#424242'
red     = '#853434'
green   = '#27583e'
yellow  = '#554f1c'
blue    = '#124c9c'
magenta = '#691fbe'
cyan    = '#2c5550'
white   = '#45433c'

[colors.bright]
black   = '#424242'
red     = '#9e0f0f'
green   = '#2c5920'
yellow  = '#77410c'
blue    = '#1e546a'
magenta = '#681fbf'
cyan    = '#2b564f'
white   = '#62390a'