# extras/alacritty/themes/abyss_light_1/oasis_abyss_light_1.toml
## name: Oasis Abyss Light 1
## author: uhs-robert

[colors.primary]
background = '#f9f5f5'
foreground = '#5f514e'

[colors.selection]
background = '#e8d8d8'
text = '#5f514e'

[colors.cursor]
cursor = '#686223'
text = '#545454'

[colors.vi_mode_cursor]
cursor = '#914f0e'
text = '#545454'

[colors.normal]
black   = '#545454'
red     = '#a33f3f'
green   = '#2f6b4c'
yellow  = '#686223'
blue    = '#155dbf'
magenta = '#7f2fdd'
cyan    = '#366961'
white   = '#57544c'

[colors.bright]
black   = '#545454'
red     = '#c01313'
green   = '#366c27'
yellow  = '#914f0e'
blue    = '#256782'
magenta = '#7e2fdd'
cyan    = '#356961'
white   = '#7b480c'