# extras/alacritty/themes/abyss_light_3/oasis_abyss_light_3.toml
## name: Oasis Abyss Light 3
## author: uhs-robert

[colors.primary]
background = '#f7dbd4'
foreground = '#514542'

[colors.selection]
background = '#f0bbad'
text = '#514542'

[colors.cursor]
cursor = '#5b551e'
text = '#484848'

[colors.vi_mode_cursor]
cursor = '#7f450c'
text = '#484848'

[colors.normal]
black   = '#484848'
red     = '#8e3838'
green   = '#2a5e42'
yellow  = '#5b551e'
blue    = '#1251a7'
magenta = '#6f21cb'
cyan    = '#305b56'
white   = '#4b4841'

[colors.bright]
black   = '#484848'
red     = '#a91111'
green   = '#2f5f22'
yellow  = '#7f450c'
blue    = '#205a71'
magenta = '#6e21cd'
cyan    = '#2e5b55'
white   = '#6a3d0a'