# extras/alacritty/themes/abyss_light_2/oasis_abyss_light_2.toml
## name: Oasis Abyss Light 2
## author: uhs-robert

[colors.primary]
background = '#f8ebe7'
foreground = '#5a4c4a'

[colors.selection]
background = '#eecdc3'
text = '#5a4c4a'

[colors.cursor]
cursor = '#635d21'
text = '#4f4f4f'

[colors.vi_mode_cursor]
cursor = '#8a4b0d'
text = '#4f4f4f'

[colors.normal]
black   = '#4f4f4f'
red     = '#9b3d3d'
green   = '#2e6648'
yellow  = '#635d21'
blue    = '#1459b5'
magenta = '#7925dc'
cyan    = '#33645e'
white   = '#524f47'

[colors.bright]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#336725'
yellow  = '#8a4b0d'
blue    = '#23627b'
magenta = '#7827db'
cyan    = '#33645c'
white   = '#74440b'