# extras/alacritty/themes/cactus_light_5/oasis_cactus_light_5.toml
## name: Oasis Cactus Light 5
## author: uhs-robert

[colors.primary]
background = '#cbebd7'
foreground = '#3c4d44'

[colors.selection]
background = '#aadebe'
text = '#3c4d44'

[colors.cursor]
cursor = '#5c561f'
text = '#494949'

[colors.vi_mode_cursor]
cursor = '#81460d'
text = '#494949'

[colors.normal]
black   = '#494949'
red     = '#903939'
green   = '#2a5f43'
yellow  = '#5c561f'
blue    = '#1352aa'
magenta = '#7221ce'
cyan    = '#305d57'
white   = '#4c4942'

[colors.bright]
black   = '#494949'
red     = '#ac1111'
green   = '#306023'
yellow  = '#81460d'
blue    = '#215b73'
magenta = '#7022cf'
cyan    = '#2f5d56'
white   = '#6b3f0b'