# extras/alacritty/themes/cactus_light_4/oasis_cactus_light_4.toml
## name: Oasis Cactus Light 4
## author: uhs-robert

[colors.primary]
background = '#d6f0e1'
foreground = '#405147'

[colors.selection]
background = '#b4e4c8'
text = '#405147'

[colors.cursor]
cursor = '#615a20'
text = '#4d4d4d'

[colors.vi_mode_cursor]
cursor = '#874a0d'
text = '#4d4d4d'

[colors.normal]
black   = '#4d4d4d'
red     = '#973b3b'
green   = '#2c6446'
yellow  = '#615a20'
blue    = '#1356b1'
magenta = '#7623d8'
cyan    = '#32615b'
white   = '#504d45'

[colors.bright]
black   = '#4d4d4d'
red     = '#b31111'
green   = '#326425'
yellow  = '#874a0d'
blue    = '#226078'
magenta = '#7523d9'
cyan    = '#32615a'
white   = '#71420b'