# extras/alacritty/themes/cactus_light_3/oasis_cactus_light_3.toml
## name: Oasis Cactus Light 3
## author: uhs-robert

[colors.primary]
background = '#e0f0e7'
foreground = '#405348'

[colors.selection]
background = '#c1e1cf'
text = '#405348'

[colors.cursor]
cursor = '#625c21'
text = '#4e4e4e'

[colors.vi_mode_cursor]
cursor = '#894b0d'
text = '#4e4e4e'

[colors.normal]
black   = '#4e4e4e'
red     = '#993c3c'
green   = '#2d6547'
yellow  = '#625c21'
blue    = '#1358b4'
magenta = '#7824da'
cyan    = '#33635d'
white   = '#514e47'

[colors.bright]
black   = '#4e4e4e'
red     = '#b51212'
green   = '#336625'
yellow  = '#894b0d'
blue    = '#23617a'
magenta = '#7725db'
cyan    = '#32635c'
white   = '#73430b'