# extras/wezterm/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors]
foreground = "#4e483f"
background= "#f5dfc7"
cursor_bg= "#5e5517"
cursor_border= "#5e5517"
cursor_fg= "#f3d8ba"
selection_bg= "#eec9a0"
selection_fg= "#f3d8ba"
split= "#4c4a34"
compose_cursor= "#674019"
scrollbar_thumb= "#eec9a0"
visual_bell= "#f3d8ba"

ansi = [
  '#494949',
  '#8f3838',
  '#2a5f43',
  '#5c561f',
  '#1252a8',
  '#7121cd',
  '#305c56',
  '#4b4941',
]

brights = [
  '#494949',
  '#aa1010',
  '#306023',
  '#80460d',
  '#205b73',
  '#7021cf',
  '#2f5d56',
  '#6b3e0b',
]

[colors.indexed]
16 = '#674019'
17 = '#9f272b'

[colors.tab_bar]
background = '#f3d8ba'
inactive_tab_edge = '#f0d0ad'

[colors.tab_bar.active_tab]
bg_color = '#5f5b2b'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eec9a0'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f3d8ba'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#326234'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1f7548'
fg_color = '#f5dfc7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 4'