# extras/wezterm/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors]
foreground = "#4e4b36"
background= "#ece6c6"
cursor_bg= "#605717"
cursor_border= "#605717"
cursor_fg= "#e8e1bb"
selection_bg= "#e1d7a4"
selection_fg= "#e8e1bb"
split= "#4e4b35"
compose_cursor= "#6a411a"
scrollbar_thumb= "#e1d7a4"
visual_bell= "#e8e1bb"

ansi = [
  '#4a4a4a',
  '#923a3a',
  '#2b6144',
  '#5e581f',
  '#1354ac',
  '#7322d1',
  '#315e58',
  '#4d4a43',
]

brights = [
  '#4a4a4a',
  '#ae1111',
  '#306123',
  '#83470d',
  '#225d75',
  '#7222d2',
  '#305f57',
  '#6d400b',
]

[colors.indexed]
16 = '#6a411a'
17 = '#a3282c'

[colors.tab_bar]
background = '#e8e1bb'
inactive_tab_edge = '#e4dcaf'

[colors.tab_bar.active_tab]
bg_color = '#585527'
fg_color = '#ece6c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e1d7a4'
fg_color = '#ece6c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e8e1bb'
fg_color = '#ece6c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#2e5c30'
fg_color = '#ece6c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1c6e43'
fg_color = '#ece6c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 5'