# extras/wezterm/oasis_dune_light_3.toml
## name: Oasis Dune Light 3
## author: uhs-robert

[colors]
foreground = "#54523b"
background= "#f4f2dd"
cursor_bg= "#695e19"
cursor_border= "#695e19"
cursor_fg= "#f0eed1"
selection_bg= "#e9e5ba"
selection_fg= "#f0eed1"
split= "#54523a"
compose_cursor= "#73471c"
scrollbar_thumb= "#e9e5ba"
visual_bell= "#f0eed1"

ansi = [
  '#515151',
  '#9e3e3e',
  '#2f684a',
  '#665f22',
  '#145ab9',
  '#7b2adc',
  '#35665f',
  '#545149',
]

brights = [
  '#515151',
  '#bb1313',
  '#356926',
  '#8d4d0e',
  '#24647e',
  '#7a2adc',
  '#34665f',
  '#77450c',
]

[colors.indexed]
16 = '#73471c'
17 = '#af2a2e'

[colors.tab_bar]
background = '#f0eed1'
inactive_tab_edge = '#ede9c6'

[colors.tab_bar.active_tab]
bg_color = '#65612f'
fg_color = '#f4f2dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9e5ba'
fg_color = '#f4f2dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f0eed1'
fg_color = '#f4f2dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#366838'
fg_color = '#f4f2dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#227c4d'
fg_color = '#f4f2dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 3'