# extras/wezterm/oasis_dune_light_2.toml
## name: Oasis Dune Light 2
## author: uhs-robert

[colors]
foreground = "#58563e"
background= "#f9f8ec"
cursor_bg= "#6d621a"
cursor_border= "#6d621a"
cursor_fg= "#f5f4e0"
selection_bg= "#eeebc9"
selection_fg= "#f5f4e0"
split= "#58563c"
compose_cursor= "#784a1c"
scrollbar_thumb= "#eeebc9"
visual_bell= "#f5f4e0"

ansi = [
  '#555555',
  '#a44040',
  '#316c4c',
  '#6a6223',
  '#155ebf',
  '#8030dd',
  '#366964',
  '#58554c',
]

brights = [
  '#555555',
  '#c21414',
  '#376d28',
  '#93500e',
  '#266883',
  '#7f31dd',
  '#366a62',
  '#7c480c',
]

[colors.indexed]
16 = '#784a1c'
17 = '#b62c30'

[colors.tab_bar]
background = '#f5f4e0'
inactive_tab_edge = '#f2efd5'

[colors.tab_bar.active_tab]
bg_color = '#6c6733'
fg_color = '#f9f8ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#eeebc9'
fg_color = '#f9f8ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f5f4e0'
fg_color = '#f9f8ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#3a6f3c'
fg_color = '#f9f8ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#258352'
fg_color = '#f9f8ec'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 2'