# extras/wezterm/oasis_dune_light_1.toml
## name: Oasis Dune Light 1
## author: uhs-robert

[colors]
foreground = "#5a5740"
background= "#fbfaf9"
cursor_bg= "#6e631a"
cursor_border= "#6e631a"
cursor_fg= "#f5f2f0"
selection_bg= "#e9e3dd"
selection_fg= "#f5f2f0"
split= "#59573d"
compose_cursor= "#7b4b1d"
scrollbar_thumb= "#e9e3dd"
visual_bell= "#f5f2f0"

ansi = [
  '#565656',
  '#a74141',
  '#306e4e',
  '#6b6424',
  '#155fc4',
  '#8133dd',
  '#386b64',
  '#59564e',
]

brights = [
  '#565656',
  '#c51414',
  '#376f28',
  '#95510e',
  '#266a86',
  '#8134de',
  '#366c63',
  '#7f4a0d',
]

[colors.indexed]
16 = '#7b4b1d'
17 = '#ba2b31'

[colors.tab_bar]
background = '#f5f2f0'
inactive_tab_edge = '#efebe7'

[colors.tab_bar.active_tab]
bg_color = '#726d36'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e9e3dd'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f5f2f0'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#3e7540'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#298a57'
fg_color = '#fbfaf9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 1'