# extras/wezterm/oasis_dune_light_4.toml
## name: Oasis Dune Light 4
## author: uhs-robert

[colors]
foreground = "#514e39"
background= "#f0ecd1"
cursor_bg= "#645a18"
cursor_border= "#645a18"
cursor_fg= "#ece7c5"
selection_bg= "#e5deae"
selection_fg= "#ece7c5"
split= "#514f37"
compose_cursor= "#6f441b"
scrollbar_thumb= "#e5deae"
visual_bell= "#ece7c5"

ansi = [
  '#4e4e4e',
  '#983c3c',
  '#2d6447',
  '#625b21',
  '#1357b2',
  '#7723da',
  '#32625c',
  '#504e46',
]

brights = [
  '#4e4e4e',
  '#b41111',
  '#336525',
  '#884a0d',
  '#226179',
  '#7623db',
  '#32625b',
  '#72430b',
]

[colors.indexed]
16 = '#6f441b'
17 = '#a9292d'

[colors.tab_bar]
background = '#ece7c5'
inactive_tab_edge = '#e8e2ba'

[colors.tab_bar.active_tab]
bg_color = '#5f5b2b'
fg_color = '#f0ecd1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#e5deae'
fg_color = '#f0ecd1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ece7c5'
fg_color = '#f0ecd1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#326234'
fg_color = '#f0ecd1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#1f7548'
fg_color = '#f0ecd1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'uhs-robert'
name = 'Oasis Dune Light 4'