# extras/alacritty/themes/dawn/oasis_dawn.toml
## name: Oasis Dawn
## author: uhs-robert

[colors.primary]
background = '#EFE5B6'
foreground = '#443725'

[colors.selection]
background = '#D7CC97'
text = '#443725'

[colors.cursor]
cursor = '#5d571f'
text = '#4a4a4a'

[colors.vi_mode_cursor]
cursor = '#82470d'
text = '#4a4a4a'

[colors.normal]
black   = '#4a4a4a'
red     = '#913939'
green   = '#2b6044'
yellow  = '#5d571f'
blue    = '#1253aa'
magenta = '#7222d0'
cyan    = '#305e59'
white   = '#4c4a42'

[colors.bright]
black   = '#4a4a4a'
red     = '#ac1111'
green   = '#306123'
yellow  = '#82470d'
blue    = '#215c74'
magenta = '#7122d1'
cyan    = '#305e57'
white   = '#6c3f0b'