# extras/alacritty/themes/light/5/oasis_cactus_light_5.toml
## name: Oasis Cactus Light 5
## author: uhs-robert

[colors.primary]
background = '#cbebd7'
foreground = '#3c4d44'

[colors.selection]
background = '#aadebe'
text = '#3c4d44'

[colors.cursor]
cursor = '#375e39'
text = '#cbebd7'

[colors.vi_mode_cursor]
cursor = '#7e4813'
text = '#cbebd7'

[colors.normal]
black   = '#494949'
red     = '#ac1111'
green   = '#2a5f43'
yellow  = '#5c561f'
blue    = '#135699'
magenta = '#7222ce'
cyan    = '#305d57'
white   = '#4c4942'

[colors.bright]
black   = '#4f4844'
red     = '#ac1111'
green   = '#306023'
yellow  = '#7e4813'
blue    = '#215b73'
magenta = '#7022cf'
cyan    = '#2f5d56'
white   = '#6b3f0b'