# extras/alacritty/themes/light/5/oasis_rose_light_5.toml
## name: Oasis Rose Light 5
## author: uhs-robert

[colors.primary]
background = '#f0c2e7'
foreground = '#4a3845'

[colors.selection]
background = '#e79dd9'
text = '#4a3845'

[colors.cursor]
cursor = '#941015'
text = '#f0c2e7'

[colors.vi_mode_cursor]
cursor = '#6d3e10'
text = '#f0c2e7'

[colors.normal]
black   = '#3d3d3d'
red     = '#950e0e'
green   = '#24523a'
yellow  = '#4f4a1a'
blue    = '#114a84'
magenta = '#621db2'
cyan    = '#29504b'
white   = '#3f3d37'

[colors.bright]
black   = '#423c38'
red     = '#940e0e'
green   = '#29531e'
yellow  = '#6d3e10'
blue    = '#1c4f63'
magenta = '#611db3'
cyan    = '#29504a'
white   = '#5a3509'