# extras/alacritty/themes/light/5/oasis_midnight_light_5.toml
## name: Oasis Midnight Light 5
## author: uhs-robert

[colors.primary]
background = '#f3cdba'
foreground = '#473f3a'

[colors.selection]
background = '#ecb193'
text = '#473f3a'

[colors.cursor]
cursor = '#941d21'
text = '#f3cdba'

[colors.vi_mode_cursor]
cursor = '#714011'
text = '#f3cdba'

[colors.normal]
black   = '#404040'
red     = '#9a0f0f'
green   = '#26553c'
yellow  = '#534d1b'
blue    = '#114d89'
magenta = '#661eb9'
cyan    = '#2b534e'
white   = '#42403a'

[colors.bright]
black   = '#463f3b'
red     = '#9a0f0f'
green   = '#2b561f'
yellow  = '#714011'
blue    = '#1e5267'
magenta = '#651fba'
cyan    = '#2a534d'
white   = '#5f370a'