# extras/alacritty/themes/light/5/oasis_twilight_light_5.toml
## name: Oasis Twilight Light 5
## author: uhs-robert

[colors.primary]
background = '#cac2f0'
foreground = '#3b3351'

[colors.selection]
background = '#aa9de7'
text = '#3b3351'

[colors.cursor]
cursor = '#6012a9'
text = '#cac2f0'

[colors.vi_mode_cursor]
cursor = '#653a0f'
text = '#cac2f0'

[colors.normal]
black   = '#383838'
red     = '#8b0d0d'
green   = '#224c36'
yellow  = '#4a4518'
blue    = '#0f457b'
magenta = '#5b1ba6'
cyan    = '#264a46'
white   = '#393832'

[colors.bright]
black   = '#3e3630'
red     = '#8a0d0d'
green   = '#264d1c'
yellow  = '#653a0f'
blue    = '#1a495c'
magenta = '#5a1ba6'
cyan    = '#264a45'
white   = '#523008'