# extras/alacritty/themes/light/5/oasis_night_light_5.toml
## name: Oasis Night Light 5
## author: uhs-robert

[colors.primary]
background = '#e0cfa3'
foreground = '#4b3b28'

[colors.selection]
background = '#d5bd81'
text = '#4b3b28'

[colors.cursor]
cursor = '#504b1a'
text = '#3e3e3e'

[colors.vi_mode_cursor]
cursor = '#6f3d0b'
text = '#3e3e3e'

[colors.normal]
black   = '#3e3e3e'
red     = '#7c3131'
green   = '#24523a'
yellow  = '#504b1a'
blue    = '#114792'
magenta = '#631db3'
cyan    = '#29504b'
white   = '#3f3d37'

[colors.bright]
black   = '#3e3e3e'
red     = '#950e0e'
green   = '#29531e'
yellow  = '#6f3d0b'
blue    = '#1d4f63'
magenta = '#621eb4'
cyan    = '#29504a'
white   = '#5a3509'