# extras/alacritty/themes/light/5/oasis_desert_light_5.toml
## name: Oasis Desert Light 5
## author: uhs-robert

[colors.primary]
background = '#f3d5ba'
foreground = '#504132'

[colors.selection]
background = '#ecbd93'
text = '#504132'

[colors.cursor]
cursor = '#595016'
text = '#f3d5ba'

[colors.vi_mode_cursor]
cursor = '#764311'
text = '#f3d5ba'

[colors.normal]
black   = '#444444'
red     = '#a11010'
green   = '#28593f'
yellow  = '#56511d'
blue    = '#125190'
magenta = '#6b1fc1'
cyan    = '#2d5752'
white   = '#46443d'

[colors.bright]
black   = '#49433f'
red     = '#a11010'
green   = '#2d5a20'
yellow  = '#764311'
blue    = '#1f566c'
magenta = '#6a20c2'
cyan    = '#2c5750'
white   = '#643a0a'