# extras/alacritty/themes/light/5/oasis_sol_light_5.toml
## name: Oasis Sol Light 5
## author: uhs-robert

[colors.primary]
background = '#f3bfba'
foreground = '#5b2e26'

[colors.selection]
background = '#ec9b93'
text = '#5b2e26'

[colors.cursor]
cursor = '#871f20'
text = '#f3bfba'

[colors.vi_mode_cursor]
cursor = '#683b0f'
text = '#f3bfba'

[colors.normal]
black   = '#3a3a3a'
red     = '#8f0e0e'
green   = '#234f38'
yellow  = '#4c4719'
blue    = '#0f477f'
magenta = '#5e1cab'
cyan    = '#274d48'
white   = '#3c3a34'

[colors.bright]
black   = '#3f3936'
red     = '#8f0e0e'
green   = '#274f1d'
yellow  = '#683b0f'
blue    = '#1b4b5f'
magenta = '#5d1cac'
cyan    = '#274d47'
white   = '#563209'