# extras/alacritty/themes/light/5/oasis_dune_light_5.toml
## name: Oasis Dune Light 5
## author: uhs-robert

[colors.primary]
background = '#ece1c6'
foreground = '#4a4940'

[colors.selection]
background = '#e1cfa4'
text = '#4a4940'

[colors.cursor]
cursor = '#5e5517'
text = '#ece1c6'

[colors.vi_mode_cursor]
cursor = '#7d4712'
text = '#ece1c6'

[colors.normal]
black   = '#484848'
red     = '#a91010'
green   = '#2a5e42'
yellow  = '#5b551e'
blue    = '#125597'
magenta = '#7021cc'
cyan    = '#2f5c57'
white   = '#4a4841'

[colors.bright]
black   = '#50473e'
red     = '#aa1111'
green   = '#2f5f22'
yellow  = '#7d4712'
blue    = '#215b72'
magenta = '#6f22cd'
cyan    = '#2f5c55'
white   = '#6a3e0b'