# extras/alacritty/themes/light/5/oasis_starlight_light_5.toml
## name: Oasis Starlight Light 5
## author: uhs-robert

[colors.primary]
background = '#f3deba'
foreground = '#4d4738'

[colors.selection]
background = '#eccb93'
text = '#4d4738'

[colors.cursor]
cursor = '#125592'
text = '#f3deba'

[colors.vi_mode_cursor]
cursor = '#7c4712'
text = '#f3deba'

[colors.normal]
black   = '#474747'
red     = '#a81010'
green   = '#2a5d42'
yellow  = '#5b551e'
blue    = '#125596'
magenta = '#6f21ca'
cyan    = '#2f5b56'
white   = '#4a4740'

[colors.bright]
black   = '#4f463d'
red     = '#a81010'
green   = '#2f5e22'
yellow  = '#7c4712'
blue    = '#205a71'
magenta = '#6e21cb'
cyan    = '#2e5b54'
white   = '#693d0b'