# extras/alacritty/themes/light/5/oasis_mirage_light_5.toml
## name: Oasis Mirage Light 5
## author: uhs-robert

[colors.primary]
background = '#c0f2ee'
foreground = '#3c5050'

[colors.selection]
background = '#9aeae4'
text = '#3c5050'

[colors.cursor]
cursor = '#31605a'
text = '#c0f2ee'

[colors.vi_mode_cursor]
cursor = '#834b13'
text = '#c0f2ee'

[colors.normal]
black   = '#4c4c4c'
red     = '#b11111'
green   = '#2c6346'
yellow  = '#605a20'
blue    = '#13599f'
magenta = '#7523d5'
cyan    = '#31605b'
white   = '#4e4c44'

[colors.bright]
black   = '#554a41'
red     = '#b11111'
green   = '#316424'
yellow  = '#834b13'
blue    = '#225f77'
magenta = '#7423d6'
cyan    = '#316159'
white   = '#70410b'