# extras/alacritty/themes/light/5/oasis_sol_light_5.toml
## name: Oasis Sol Light 5
## author: uhs-robert

[colors.primary]
background = '#f3bfba'
foreground = '#5b2e26'

[colors.selection]
background = '#ec9b93'
text = '#5b2e26'

[colors.cursor]
cursor = '#4c4719'
text = '#3a3a3a'

[colors.vi_mode_cursor]
cursor = '#6b3a0b'
text = '#3a3a3a'

[colors.normal]
black   = '#3a3a3a'
red     = '#772f2f'
green   = '#234f38'
yellow  = '#4c4719'
blue    = '#10448c'
magenta = '#5f1cac'
cyan    = '#284d48'
white   = '#3c3a34'

[colors.bright]
black   = '#3a3a3a'
red     = '#8f0e0e'
green   = '#274f1d'
yellow  = '#6b3a0b'
blue    = '#1b4b5f'
magenta = '#5d1cac'
cyan    = '#274d47'
white   = '#563209'