# extras/alacritty/themes/light/5/oasis_lagoon_light_5.toml
## name: Oasis Lagoon Light 5
## author: uhs-robert

[colors.primary]
background = '#bcd6f5'
foreground = '#30405b'

[colors.selection]
background = '#94beef'
text = '#30405b'

[colors.cursor]
cursor = '#104d84'
text = '#bcd6f5'

[colors.vi_mode_cursor]
cursor = '#704010'
text = '#bcd6f5'

[colors.normal]
black   = '#404040'
red     = '#803232'
green   = '#26543c'
yellow  = '#524d1b'
blue    = '#114997'
magenta = '#651eb8'
cyan    = '#2b524d'
white   = '#413f39'

[colors.bright]
black   = '#453e3a'
red     = '#990f0f'
green   = '#2a551f'
yellow  = '#704010'
blue    = '#1d5166'
magenta = '#641eb8'
cyan    = '#2a534c'
white   = '#5d3609'