# extras/alacritty/themes/light/3/oasis_abyss_light_3.toml
## name: Oasis Abyss Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e5d4'
foreground = '#524b43'

[colors.selection]
background = '#f0cead'
text = '#524b43'

[colors.cursor]
cursor = '#ab1e22'
text = '#f7e5d4'

[colors.vi_mode_cursor]
cursor = '#824a14'
text = '#f7e5d4'

[colors.normal]
black   = '#4c4c4c'
red     = '#b01212'
green   = '#2c6245'
yellow  = '#605920'
blue    = '#13599e'
magenta = '#7523d5'
cyan    = '#31605b'
white   = '#4f4c44'

[colors.bright]
black   = '#524b45'
red     = '#b01212'
green   = '#326324'
yellow  = '#824a14'
blue    = '#225f77'
magenta = '#7423d6'
cyan    = '#316059'
white   = '#70410b'