# extras/alacritty/themes/light/3/oasis_midnight_light_3.toml
## name: Oasis Midnight Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e2d4'
foreground = '#524943'

[colors.selection]
background = '#f0c8ad'
text = '#524943'

[colors.cursor]
cursor = '#a52429'
text = '#f7e2d4'

[colors.vi_mode_cursor]
cursor = '#804913'
text = '#f7e2d4'

[colors.normal]
black   = '#4b4b4b'
red     = '#a52525'
green   = '#2b6144'
yellow  = '#5f581d'
blue    = '#13589c'
magenta = '#7323d2'
cyan    = '#315e59'
white   = '#4e4b43'

[colors.bright]
black   = '#514a44'
red     = '#ae1212'
green   = '#316223'
yellow  = '#804913'
blue    = '#215d75'
magenta = '#7223d3'
cyan    = '#305f58'
white   = '#6e400b'