# extras/alacritty/themes/light/3/oasis_lagoon_light_3.toml
## name: Oasis Lagoon Light 3
## author: uhs-robert

[colors.primary]
background = '#d9e5f7'
foreground = '#384b68'

[colors.selection]
background = '#b3cbef'
text = '#384b68'

[colors.cursor]
cursor = '#5d571f'
text = '#4a4a4a'

[colors.vi_mode_cursor]
cursor = '#82470d'
text = '#4a4a4a'

[colors.normal]
black   = '#4a4a4a'
red     = '#913939'
green   = '#2b6044'
yellow  = '#5d571f'
blue    = '#1253aa'
magenta = '#7222cf'
cyan    = '#315d58'
white   = '#4d4a42'

[colors.bright]
black   = '#4a4a4a'
red     = '#ac1111'
green   = '#306023'
yellow  = '#82470d'
blue    = '#215c74'
magenta = '#7122d1'
cyan    = '#2f5d57'
white   = '#6c3f0b'