# extras/alacritty/themes/light/3/oasis_mirage_light_3.toml
## name: Oasis Mirage Light 3
## author: uhs-robert

[colors.primary]
background = '#dbf5f5'
foreground = '#405454'

[colors.selection]
background = '#b7ebeb'
text = '#405454'

[colors.cursor]
cursor = '#32655d'
text = '#dbf5f5'

[colors.vi_mode_cursor]
cursor = '#894e15'
text = '#dbf5f5'

[colors.normal]
black   = '#505050'
red     = '#9d3e3e'
green   = '#2e6749'
yellow  = '#655e21'
blue    = '#145ab8'
magenta = '#7b28dc'
cyan    = '#34655f'
white   = '#535048'

[colors.bright]
black   = '#574f49'
red     = '#b91313'
green   = '#346926'
yellow  = '#894e15'
blue    = '#24647d'
magenta = '#7929dc'
cyan    = '#33655e'
white   = '#76450c'