# extras/alacritty/themes/light/3/oasis_desert_light_3.toml
## name: Oasis Desert Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e7d4'
foreground = '#5a4a38'

[colors.selection]
background = '#f0d1ad'
text = '#5a4a38'

[colors.cursor]
cursor = '#615a20'
text = '#4d4d4d'

[colors.vi_mode_cursor]
cursor = '#86490d'
text = '#4d4d4d'

[colors.normal]
black   = '#4d4d4d'
red     = '#963b3b'
green   = '#2c6346'
yellow  = '#615a20'
blue    = '#1356b0'
magenta = '#7623d7'
cyan    = '#32615b'
white   = '#504d45'

[colors.bright]
black   = '#4d4d4d'
red     = '#b21212'
green   = '#326424'
yellow  = '#86490d'
blue    = '#225f77'
magenta = '#7523d8'
cyan    = '#31615a'
white   = '#71420b'