# extras/alacritty/themes/light/3/oasis_canyon_light_3.toml
## name: Oasis Canyon Light 3
## author: uhs-robert

[colors.primary]
background = '#f7e7d4'
foreground = '#5d4a33'

[colors.selection]
background = '#f0d1ad'
text = '#5d4a33'

[colors.cursor]
cursor = '#89480f'
text = '#f7e7d4'

[colors.vi_mode_cursor]
cursor = '#834b14'
text = '#f7e7d4'

[colors.normal]
black   = '#4d4d4d'
red     = '#963b3b'
green   = '#2c6346'
yellow  = '#615a20'
blue    = '#1356b0'
magenta = '#7623d7'
cyan    = '#32615b'
white   = '#504d45'

[colors.bright]
black   = '#534c46'
red     = '#b21212'
green   = '#326424'
yellow  = '#834b14'
blue    = '#225f77'
magenta = '#7523d8'
cyan    = '#31615a'
white   = '#71420b'