# extras/alacritty/themes/light/3/oasis_twilight_light_3.toml
## name: Oasis Twilight Light 3
## author: uhs-robert

[colors.primary]
background = '#e2ddf4'
foreground = '#4a4268'

[colors.selection]
background = '#c4bae9'
text = '#4a4268'

[colors.cursor]
cursor = '#7416cd'
text = '#e2ddf4'

[colors.vi_mode_cursor]
cursor = '#7b4612'
text = '#e2ddf4'

[colors.normal]
black   = '#474747'
red     = '#a71111'
green   = '#2a5d42'
yellow  = '#5b541e'
blue    = '#125496'
magenta = '#6f21ca'
cyan    = '#2e5b56'
white   = '#4a4740'

[colors.bright]
black   = '#4f453e'
red     = '#a71111'
green   = '#2f5e22'
yellow  = '#7b4612'
blue    = '#205970'
magenta = '#6d21cb'
cyan    = '#2e5b54'
white   = '#693d0a'