# extras/alacritty/themes/light/3/oasis_starlight_light_3.toml
## name: Oasis Starlight Light 3
## author: uhs-robert

[colors.primary]
background = '#f4eddd'
foreground = '#564f3e'

[colors.selection]
background = '#e9dbba'
text = '#564f3e'

[colors.cursor]
cursor = '#135d9e'
text = '#f4eddd'

[colors.vi_mode_cursor]
cursor = '#874d14'
text = '#f4eddd'

[colors.normal]
black   = '#4f4f4f'
red     = '#b71212'
green   = '#2e6648'
yellow  = '#645d21'
blue    = '#145ca4'
magenta = '#7924dc'
cyan    = '#33635e'
white   = '#524f47'

[colors.bright]
black   = '#554e48'
red     = '#b71212'
green   = '#336725'
yellow  = '#874d14'
blue    = '#23627b'
magenta = '#7826dc'
cyan    = '#33645d'
white   = '#74440b'