# extras/alacritty/themes/light/3/oasis_dune_light_3.toml
## name: Oasis Dune Light 3
## author: uhs-robert

[colors.primary]
background = '#f4efdd'
foreground = '#525047'

[colors.selection]
background = '#e9dfba'
text = '#525047'

[colors.cursor]
cursor = '#685c19'
text = '#f4efdd'

[colors.vi_mode_cursor]
cursor = '#884e14'
text = '#f4efdd'

[colors.normal]
black   = '#505050'
red     = '#af2828'
green   = '#2e6749'
yellow  = '#645d1f'
blue    = '#145da6'
magenta = '#7a27db'
cyan    = '#34645e'
white   = '#535048'

[colors.bright]
black   = '#574f49'
red     = '#b81313'
green   = '#346826'
yellow  = '#884e14'
blue    = '#23637c'
magenta = '#7928dc'
cyan    = '#33645d'
white   = '#76440b'