# extras/alacritty/themes/light/3/oasis_sol_light_3.toml
## name: Oasis Sol Light 3
## author: uhs-robert

[colors.primary]
background = '#f7d9d4'
foreground = '#6d382e'

[colors.selection]
background = '#f0b7ad'
text = '#6d382e'

[colors.cursor]
cursor = '#9f2326'
text = '#f7d9d4'

[colors.vi_mode_cursor]
cursor = '#7b4612'
text = '#f7d9d4'

[colors.normal]
black   = '#474747'
red     = '#9e2424'
green   = '#295d41'
yellow  = '#5a541c'
blue    = '#125496'
magenta = '#6e21c9'
cyan    = '#2f5a55'
white   = '#4a4740'

[colors.bright]
black   = '#4d4641'
red     = '#a71111'
green   = '#2f5e22'
yellow  = '#7b4612'
blue    = '#205970'
magenta = '#6d21ca'
cyan    = '#2e5b54'
white   = '#683d0a'