# extras/alacritty/themes/light/3/oasis_night_light_3.toml
## name: Oasis Night Light 3
## author: uhs-robert

[colors.primary]
background = '#e6dbb2'
foreground = '#52412d'

[colors.selection]
background = '#dbca8f'
text = '#52412d'

[colors.cursor]
cursor = '#7c410d'
text = '#e6dbb2'

[colors.vi_mode_cursor]
cursor = '#774412'
text = '#e6dbb2'

[colors.normal]
black   = '#623b14'
red     = '#a11010'
green   = '#285a3f'
yellow  = '#57511d'
blue    = '#125190'
magenta = '#6b20c3'
cyan    = '#2d5753'
white   = '#47443d'

[colors.bright]
black   = '#573f30'
red     = '#a11010'
green   = '#2d5a21'
yellow  = '#774412'
blue    = '#1f566c'
magenta = '#6a20c4'
cyan    = '#2c5851'
white   = '#643a0a'