# extras/alacritty/themes/light/3/oasis_rose_light_3.toml
## name: Oasis Rose Light 3
## author: uhs-robert

[colors.primary]
background = '#f4ddee'
foreground = '#594353'

[colors.selection]
background = '#e9badd'
text = '#594353'

[colors.cursor]
cursor = '#5d561f'
text = '#494949'

[colors.vi_mode_cursor]
cursor = '#81470d'
text = '#494949'

[colors.normal]
black   = '#494949'
red     = '#903939'
green   = '#2b5f43'
yellow  = '#5d561f'
blue    = '#1253a9'
magenta = '#7122cf'
cyan    = '#305d57'
white   = '#4c4942'

[colors.bright]
black   = '#494949'
red     = '#ab1111'
green   = '#306023'
yellow  = '#81470d'
blue    = '#215c73'
magenta = '#7022d0'
cyan    = '#2f5d57'
white   = '#6c3f0b'